CREATE TABLE [dbo].[afrc_oracle_nonunit_PERSONNEL_data] (
    [PERS_ID]         VARCHAR (4000) NULL,
    [USERNAME]        VARCHAR (4000) NULL,
    [NAME]            VARCHAR (4000) NULL,
    [FIRST_NAME]      VARCHAR (4000) NULL,
    [MI]              VARCHAR (4000) NULL,
    [LAST_NAME]       VARCHAR (4000) NULL,
    [NAME_SUFFIX]     VARCHAR (4000) NULL,
    [CREATED_BY]      VARCHAR (4000) NULL,
    [CREATED_DATE]    VARCHAR (4000) NULL,
    [MODIFIED_BY]     VARCHAR (4000) NULL,
    [MODIFIED_DATE]   VARCHAR (4000) NULL,
    [CS_ID]           VARCHAR (4000) NULL,
    [DUTY_SECTION]    VARCHAR (4000) NULL,
    [SEX]             VARCHAR (4000) NULL,
    [E_MAIL_HOME]     VARCHAR (4000) NULL,
    [E_MAIL_WORK]     VARCHAR (4000) NULL,
    [E_MAIL_UNIT]     VARCHAR (4000) NULL,
    [CONTACT_INFO]    VARCHAR (4000) NULL,
    [RES_ADDRESS1]    VARCHAR (4000) NULL,
    [RES_ADDRESS2]    VARCHAR (4000) NULL,
    [RES_CITY]        VARCHAR (4000) NULL,
    [RES_POSTAL_CODE] VARCHAR (4000) NULL,
    [RES_COUNTRY]     VARCHAR (4000) NULL,
    [RES_STATE]       VARCHAR (4000) NULL
);
GO

