CREATE TABLE [dbo].[afrc_oracle_person_process_data] (
    [PP_ID]          VARCHAR (4000) NULL,
    [PI_ID]          VARCHAR (4000) NULL,
    [PROCESS_NAME]   VARCHAR (4000) NULL,
    [PVS_ID]         VARCHAR (4000) NULL,
    [STATUS_MEANING] VARCHAR (4000) NULL,
    [LOD_ID]         VARCHAR (4000) NULL,
    [PROCESSED_BY]   VARCHAR (4000) NULL,
    [START_DATE]     VARCHAR (4000) NULL,
    [END_DATE]       VARCHAR (4000) NULL,
    [COMPLETED_YN]   VARCHAR (4000) NULL,
    [FINAL_RESULT]   VARCHAR (4000) NULL,
    [REMARK]         VARCHAR (4000) NULL,
    [CREATED_BY]     VARCHAR (4000) NULL,
    [CREATED_DATE]   VARCHAR (4000) NULL,
    [MODIFIED_BY]    VARCHAR (4000) NULL,
    [MODIFIED_DATE]  VARCHAR (4000) NULL,
    [CALLING_PP_ID]  VARCHAR (4000) NULL
);
GO

