CREATE TABLE [dbo].[Form348_Audit] (
    [AuditID]                    INT             IDENTITY (1, 1) NOT NULL,
    [LOD_ID]                     INT             NOT NULL,
    [CaseID]                     VARCHAR (50)    NOT NULL,
    [Workflow]                   INT             NOT NULL,
    [MedicallyAppropriate]       SMALLINT        NULL,
    [SG_DX]                      BIT             NULL,
    [SG_ISupport]                BIT             NULL,
    [SG_EPTS]                    BIT             NULL,
    [SG_Aggravation]             BIT             NULL,
    [SG_Principles]              BIT             NULL,
    [SG_Other]                   NVARCHAR (1000) NULL,
    [SG_ProofApplied]            SMALLINT        NULL,
    [SG_CorrectStandard]         SMALLINT        NULL,
    [SG_ProofMet]                SMALLINT        NULL,
    [SG_Evidence]                SMALLINT        NULL,
    [SG_Misconduct]              SMALLINT        NULL,
    [SG_FormalInvestigation]     SMALLINT        NULL,
    [LegallySufficient]          SMALLINT        NULL,
    [JA_StandardOfProof]         BIT             NULL,
    [JA_DeathAndMVA]             BIT             NULL,
    [JA_FormalPolicy]            BIT             NULL,
    [JA_AFI]                     BIT             NULL,
    [JA_Other]                   NVARCHAR (1000) NULL,
    [JA_ProofApplied]            SMALLINT        NULL,
    [JA_CorrectStandard]         SMALLINT        NULL,
    [JA_ProofMet]                SMALLINT        NULL,
    [JA_Evidence]                SMALLINT        NULL,
    [JA_Misconduct]              SMALLINT        NULL,
    [JA_FormalInvestigation]     SMALLINT        NULL,
    [StatusValidated]            SMALLINT        NULL,
    [StatusOfMember]             BIT             NULL,
    [Orders]                     BIT             NULL,
    [A1_EPTS]                    BIT             NULL,
    [IDT]                        BIT             NULL,
    [PCARS]                      BIT             NULL,
    [EightYearRule]              BIT             NULL,
    [A1_Other]                   NVARCHAR (1000) NULL,
    [LODInitiation]              SMALLINT        NULL,
    [WrittenDiagnosis]           SMALLINT        NULL,
    [MemberRequest]              SMALLINT        NULL,
    [IncurredOrAggravated]       SMALLINT        NULL,
    [IllnessOrDisease]           SMALLINT        NULL,
    [Activites]                  INT             NULL,
    [A1_Comment]                 NVARCHAR (1000) NULL,
    [JA_Comment]                 NVARCHAR (1000) NULL,
    [SG_Comment]                 NVARCHAR (1000) NULL,
    [Determination]              INT             NULL,
    [A1_DeterminationNotCorrect] INT             NULL
);
GO

ALTER TABLE [dbo].[Form348_Audit]
    ADD CONSTRAINT [PK_Form348_Audit] PRIMARY KEY CLUSTERED ([AuditID] ASC);
GO

