CREATE TABLE [dbo].[Form348_AP] (
    [appeal_id]                       INT             IDENTITY (1, 1) NOT NULL,
    [initial_lod_id]                  INT             NOT NULL,
    [case_id]                         VARCHAR (50)    NOT NULL,
    [created_by]                      INT             NOT NULL,
    [created_date]                    DATETIME        NOT NULL,
    [modified_by]                     INT             NULL,
    [modified_date]                   DATETIME        NULL,
    [workflow]                        INT             NULL,
    [status]                          INT             NULL,
    [cancel_reason]                   INT             NULL,
    [cancel_explanation]              NVARCHAR (1000) NULL,
    [cancel_date]                     DATETIME        NULL,
    [rwoa_reason]                     TINYINT         NULL,
    [rwoa_date]                       DATETIME        NULL,
    [rwoa_explanation]                VARCHAR (MAX)   NULL,
    [return_to_group]                 INT             NULL,
    [return_by_group]                 INT             NULL,
    [sig_date_pm]                     DATETIME        NULL,
    [sig_name_pm]                     VARCHAR (100)   NULL,
    [sig_title_pm]                    NVARCHAR (100)  NULL,
    [sig_date_board_tech]             DATETIME        NULL,
    [sig_name_board_tech]             VARCHAR (100)   NULL,
    [sig_title_board_tech]            NVARCHAR (100)  NULL,
    [sig_date_board_medical]          DATETIME        NULL,
    [sig_name_board_medical]          VARCHAR (100)   NULL,
    [sig_title_board_medical]         NVARCHAR (100)  NULL,
    [sig_date_board_legal]            DATETIME        NULL,
    [sig_name_board_legal]            VARCHAR (100)   NULL,
    [sig_title_board_legal]           NVARCHAR (100)  NULL,
    [sig_date_board_admin]            DATETIME        NULL,
    [sig_name_board_admin]            VARCHAR (100)   NULL,
    [sig_title_board_admin]           NVARCHAR (100)  NULL,
    [sig_date_approving_auth]         DATETIME        NULL,
    [sig_name_approving_auth]         VARCHAR (100)   NULL,
    [sig_title_approving_auth]        NVARCHAR (100)  NULL,
    [sig_date_appellate_auth]         DATETIME        NULL,
    [sig_name_appellate_auth]         VARCHAR (100)   NULL,
    [sig_title_appellate_auth]        NVARCHAR (100)  NULL,
    [lod_pm_approved]                 TINYINT         NULL,
    [board_tech_approved]             TINYINT         NULL,
    [board_medical_approved]          TINYINT         NULL,
    [board_legal_approved]            TINYINT         NULL,
    [board_admin_approved]            TINYINT         NULL,
    [approval_auth_approved]          TINYINT         NULL,
    [appellate_auth_approved]         TINYINT         NULL,
    [lod_pm_approval_comment]         NVARCHAR (2000) NULL,
    [board_tech_approval_comment]     NVARCHAR (2000) NULL,
    [board_medical_approval_comment]  NVARCHAR (2000) NULL,
    [board_legal_approval_comment]    NVARCHAR (2000) NULL,
    [board_admin_approval_comment]    NVARCHAR (2000) NULL,
    [approval_auth_approval_comment]  NVARCHAR (2000) NULL,
    [appellate_auth_approval_comment] NVARCHAR (2000) NULL,
    [return_comment]                  NVARCHAR (2000) NULL,
    [member_ssn]                      NVARCHAR (9)    NULL,
    [member_name]                     NVARCHAR (100)  NULL,
    [doc_group_id]                    INT             NULL,
    [member_notified]                 BIT             DEFAULT ((0)) NULL,
    [is_post_processing_complete]     BIT             DEFAULT ((0)) NOT NULL,
    [member_unit]                     NVARCHAR (100)  DEFAULT ('') NOT NULL,
    [member_unit_id]                  INT             DEFAULT ((0)) NOT NULL,
    [member_compo]                    CHAR (1)        DEFAULT ('') NOT NULL,
    [member_grade]                    INT             DEFAULT ((99)) NOT NULL,
    [is_non_dbsign_case]              BIT             DEFAULT ((0)) NOT NULL
);
GO

ALTER TABLE [dbo].[Form348_AP]
    ADD CONSTRAINT [PK_Form348_AP] PRIMARY KEY CLUSTERED ([appeal_id] ASC);
GO

ALTER TABLE [dbo].[Form348_AP]
    ADD CONSTRAINT [FK_Form348_AP_core_lkupGrade] FOREIGN KEY ([member_grade]) REFERENCES [dbo].[core_lkupGrade] ([CODE]);
GO

