CREATE TABLE [dbo].[Form348_SARC_ICD] (
    [Id]         INT         IDENTITY (1, 1) NOT NULL,
    [SARCId]     INT         NOT NULL,
    [ICDCodeId]  INT         NOT NULL,
    [ICD7thChar] VARCHAR (7) NULL
);
GO

ALTER TABLE [dbo].[Form348_SARC_ICD]
    ADD CONSTRAINT [PK_Form348_SARC_ICD] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90);
GO

ALTER TABLE [dbo].[Form348_SARC_ICD]
    ADD CONSTRAINT [FK_Form348_SARC_ICD_Form348_SARC] FOREIGN KEY ([SARCId]) REFERENCES [dbo].[Form348_SARC] ([sarc_id]);
GO

ALTER TABLE [dbo].[Form348_SARC_ICD]
    ADD CONSTRAINT [FK_Form348_SARC_ICD_core_lkupICD9] FOREIGN KEY ([ICDCodeId]) REFERENCES [dbo].[core_lkupICD9] ([ICD9_ID]);
GO

