CREATE TABLE [dbo].[imp_person_processes] (
    [PP_ID]          NVARCHAR (50)   NULL,
    [PI_ID]          NVARCHAR (50)   NULL,
    [PROCESS_NAME]   NVARCHAR (4000) NULL,
    [PVS_ID]         NVARCHAR (50)   NULL,
    [STATUS_MEANING] NVARCHAR (4000) NULL,
    [LOD_ID]         NVARCHAR (50)   NULL,
    [PROCESSED_BY]   NVARCHAR (50)   NULL,
    [START_DATE]     DATETIME        NULL,
    [END_DATE]       DATETIME        NULL,
    [COMPLETED_YN]   NVARCHAR (50)   NULL,
    [FINAL_RESULT]   NVARCHAR (4000) NULL,
    [REMARK]         NVARCHAR (4000) NULL,
    [CREATED_BY]     NVARCHAR (50)   NULL,
    [CREATED_DATE]   NVARCHAR (50)   NULL,
    [MODIFIED_BY]    NVARCHAR (50)   NULL,
    [MODIFIED_DATE]  NVARCHAR (50)   NULL,
    [CALLING_PP_ID]  NVARCHAR (50)   NULL
);
GO

