CREATE TABLE [dbo].[imp_non_unit_PERSONNEL] (
    [PERS_ID]         NVARCHAR (50)   NULL,
    [USERNAME]        NVARCHAR (50)   NULL,
    [NAME]            NVARCHAR (50)   NULL,
    [FIRST_NAME]      NVARCHAR (50)   NULL,
    [MI]              NVARCHAR (50)   NULL,
    [LAST_NAME]       NVARCHAR (50)   NULL,
    [NAME_SUFFIX]     NVARCHAR (50)   NULL,
    [CREATED_BY]      NVARCHAR (50)   NULL,
    [CREATED_DATE]    NVARCHAR (50)   NULL,
    [MODIFIED_BY]     NVARCHAR (50)   NULL,
    [MODIFIED_DATE]   NVARCHAR (50)   NULL,
    [CS_ID]           NVARCHAR (50)   NULL,
    [DUTY_SECTION]    NVARCHAR (50)   NULL,
    [SEX]             NVARCHAR (50)   NULL,
    [E_MAIL_HOME]     NVARCHAR (4000) NULL,
    [E_MAIL_WORK]     NVARCHAR (4000) NULL,
    [E_MAIL_UNIT]     NVARCHAR (4000) NULL,
    [CONTACT_INFO]    NVARCHAR (4000) NULL,
    [RES_ADDRESS1]    NVARCHAR (4000) NULL,
    [RES_ADDRESS2]    NVARCHAR (4000) NULL,
    [RES_CITY]        NVARCHAR (50)   NULL,
    [RES_POSTAL_CODE] NVARCHAR (50)   NULL,
    [RES_COUNTRY]     NVARCHAR (50)   NULL,
    [RES_STATE]       NVARCHAR (50)   NULL
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_PK_USERNAME]
    ON [dbo].[imp_non_unit_PERSONNEL]([USERNAME] ASC) WITH (FILLFACTOR = 90);
GO

