CREATE TABLE [dbo].[imp_PERSONNEL_FEED_old] (
    [CAFSC]            VARCHAR (50) NULL,
    [CAFSC_PFX]        VARCHAR (50) NULL,
    [CAFSC_SFX]        VARCHAR (50) NULL,
    [CIV_ART_ID]       VARCHAR (50) NULL,
    [CLEARANCE_ID]     VARCHAR (50) NULL,
    [CREATED_BY]       VARCHAR (50) NULL,
    [CREATED_DATE]     VARCHAR (50) NULL,
    [DAFSC]            VARCHAR (50) NULL,
    [DAFSC_PFX]        VARCHAR (50) NULL,
    [DAFSC_SFX]        VARCHAR (50) NULL,
    [DAV_CODE]         VARCHAR (50) NULL,
    [DOA]              VARCHAR (50) NULL,
    [DOB]              VARCHAR (50) NULL,
    [DOE]              VARCHAR (50) NULL,
    [DOR]              VARCHAR (50) NULL,
    [DUTY_LOC]         VARCHAR (50) NULL,
    [ETS]              VARCHAR (50) NULL,
    [FIRST_NAME]       VARCHAR (50) NULL,
    [FLYER_ID]         VARCHAR (50) NULL,
    [HOME_PHONE]       VARCHAR (50) NULL,
    [LAST_NAME]        VARCHAR (50) NULL,
    [MAIL_ADDRESS1]    VARCHAR (50) NULL,
    [MAIL_ADDRESS2]    VARCHAR (50) NULL,
    [MAIL_CITY]        VARCHAR (50) NULL,
    [MAIL_POSTAL_CODE] VARCHAR (50) NULL,
    [MAIL_STATE]       VARCHAR (50) NULL,
    [MI]               VARCHAR (50) NULL,
    [MODIFIED_BY]      VARCHAR (50) NULL,
    [MODIFIED_DATE]    VARCHAR (50) NULL,
    [NAME]             VARCHAR (50) NULL,
    [NAME_SUFFIX]      VARCHAR (50) NULL,
    [PAFSC]            VARCHAR (50) NULL,
    [PAFSC_PFX]        VARCHAR (50) NULL,
    [PAFSC_SFX]        VARCHAR (50) NULL,
    [PAS_ATCH_TRNG]    VARCHAR (50) NULL,
    [PERS_ID]          VARCHAR (50) NULL,
    [POS_NBR]          VARCHAR (50) NULL,
    [RANK]             VARCHAR (50) NULL,
    [SAFSC]            VARCHAR (50) NULL,
    [SAFSC_PFX]        VARCHAR (50) NULL,
    [SAFSC_SFX]        VARCHAR (50) NULL,
    [SEI]              VARCHAR (50) NULL,
    [TAFSC]            VARCHAR (50) NULL,
    [TAFSC_PFX]        VARCHAR (50) NULL,
    [TAFSC_SFX]        VARCHAR (50) NULL,
    [TRNG_AFSC]        VARCHAR (50) NULL,
    [Column 46]        VARCHAR (50) NULL
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_PERS_ID]
    ON [dbo].[imp_PERSONNEL_FEED_old]([PERS_ID] ASC) WITH (FILLFACTOR = 90);
GO

