CREATE TABLE [dbo].[imp_LOD_ACTIVE_DUTY] (
    [AD_ID]           NVARCHAR (50) NULL,
    [SSN]             NVARCHAR (50) NULL,
    [FIRST_NAME]      NVARCHAR (50) NULL,
    [MIDDLE_INITIAL]  NVARCHAR (50) NULL,
    [LAST_NAME]       NVARCHAR (50) NULL,
    [RANK]            NVARCHAR (50) NULL,
    [DUTY_TITLE]      NVARCHAR (50) NULL,
    [AFSC]            NVARCHAR (50) NULL,
    [EMAIL]           NVARCHAR (50) NULL,
    [TELEPHONE]       NVARCHAR (50) NULL,
    [UNIT]            NVARCHAR (50) NULL,
    [UNIT_ADDRESS]    NVARCHAR (50) NULL,
    [EXPIRATION_DATE] NVARCHAR (50) NULL,
    [CREATED_DATE]    NVARCHAR (50) NULL,
    [CREATED_BY]      NVARCHAR (50) NULL,
    [MODIFIED_DATE]   NVARCHAR (50) NULL,
    [MODIFIED_BY]     NVARCHAR (50) NULL
);
GO

