CREATE TABLE [dbo].[MemberData_ChangeHistory] (
    [SSAN]                     VARCHAR (11)  NOT NULL,
    [FIRST_NAME]               VARCHAR (50)  NULL,
    [MIDDLE_NAMES]             VARCHAR (60)  NULL,
    [LAST_NAME]                VARCHAR (50)  NULL,
    [SUFFIX]                   VARCHAR (30)  NULL,
    [PAS_GAINING]              VARCHAR (8)   NULL,
    [ASG_REPT_NLT_DATE]        DATETIME      NULL,
    [RCD_ID]                   VARCHAR (2)   NULL,
    [REC_STAT_CURR]            VARCHAR (2)   NULL,
    [PAS]                      VARCHAR (8)   NULL,
    [COMM_DUTY_PHONE]          VARCHAR (12)  NULL,
    [OFFICE_SYMBOL]            VARCHAR (8)   NULL,
    [LOCAL_ADDR_STREET]        VARCHAR (200) NULL,
    [LOCAL_ADDR_CITY]          VARCHAR (40)  NULL,
    [LOCAL_ADDR_STATE]         VARCHAR (2)   NULL,
    [HOME_PHONE]               VARCHAR (20)  NULL,
    [ADRS_MAIL_DOM_CITY]       VARCHAR (40)  NULL,
    [ADRS_MAIL_DOM_STATE]      VARCHAR (2)   NULL,
    [ADRS_MAIL_ZIP]            VARCHAR (10)  NULL,
    [GR_CURR]                  INT           NULL,
    [DY_POSN_NR]               VARCHAR (9)   NULL,
    [DAFSC]                    VARCHAR (7)   NULL,
    [DUTY_STATUS]              VARCHAR (2)   NULL,
    [DUTY_STATUS_EFF_DATE]     DATETIME      NULL,
    [DUTY_STATUS_EXP_DATE]     DATETIME      NULL,
    [DEPL_AVAIL_STATUS_ADMIN]  VARCHAR (2)   NULL,
    [DEPL_AVAIL_STATUS_A_EX_D] DATETIME      NULL,
    [DEPL_AVAIL_STATUS_PHYS]   VARCHAR (2)   NULL,
    [DEPL_AVAIL_STATUS_P_EX_D] DATETIME      NULL,
    [DEPL_AVAIL_STATUS_LEGAL]  VARCHAR (2)   NULL,
    [DEPL_AVAIL_STATUS_L_EX_D] DATETIME      NULL,
    [DEPL_AVAIL_STATUS_TIME]   VARCHAR (2)   NULL,
    [DEPL_AVAIL_STATUS_T_EX_D] DATETIME      NULL,
    [PAFSC]                    VARCHAR (7)   NULL,
    [AFSC2]                    VARCHAR (7)   NULL,
    [AFSC3]                    VARCHAR (7)   NULL,
    [SEX_SVC_MBR]              VARCHAR (1)   NULL,
    [DOB]                      DATETIME      NULL,
    [RET_SEP_EFF_DATE_PROJ]    DATETIME      NULL,
    [DOS]                      DATETIME      NULL,
    [SVC_COMP]                 VARCHAR (1)   NULL,
    [TAFCSD]                   DATETIME      NULL,
    [TAFMSD]                   DATETIME      NULL,
    [ETS]                      DATETIME      NULL,
    [PAS_NUMBER]               VARCHAR (4)   NULL,
    [ZIP]                      VARCHAR (10)  NULL,
    [ChangeType]               VARCHAR (1)   NOT NULL,
    [Date]                     DATETIME      NOT NULL,
    [ATTACH_PAS]               VARCHAR (8)   NULL
);
GO

