CREATE TABLE [dbo].[MILPDSRawData] (
    [SSAN]                     VARCHAR (50)  NOT NULL,
    [FIRST_NAME]               VARCHAR (50)  NULL,
    [MIDDLE_NAMES]             VARCHAR (50)  NULL,
    [LAST_NAME]                VARCHAR (50)  NULL,
    [SUFFIX]                   VARCHAR (50)  NULL,
    [PAS_GAINING]              VARCHAR (50)  NULL,
    [ASG_REPT_NLT_DATE]        DATE          NULL,
    [RCD_ID]                   VARCHAR (50)  NULL,
    [REC_STAT_CURR]            VARCHAR (50)  NULL,
    [PAS]                      VARCHAR (50)  NULL,
    [COMM_DUTY_PHONE]          VARCHAR (50)  NULL,
    [OFFICE_SYMBOL]            VARCHAR (50)  NULL,
    [LOCAL_ADDR_CITY]          VARCHAR (50)  NULL,
    [LOCAL_ADDR_STATE]         VARCHAR (50)  NULL,
    [HOME_PHONE]               VARCHAR (50)  NULL,
    [ADRS_MAIL_DOM_CITY]       VARCHAR (50)  NULL,
    [DRS_MAIL_DOM_STATE]       VARCHAR (50)  NULL,
    [ADRS_MAIL_ZIP]            VARCHAR (50)  NULL,
    [GR_CURR]                  VARCHAR (50)  NULL,
    [DY_POSN_NR]               VARCHAR (50)  NULL,
    [DAFSC]                    VARCHAR (50)  NULL,
    [DUTY_STATUS]              VARCHAR (70)  NULL,
    [DUTY_STATUS_EFF_DATE]     VARCHAR (50)  NULL,
    [DUTY_STATUS_EXP_DATE]     DATE          NULL,
    [DEPL_AVAIL_STATUS_ADMIN]  VARCHAR (50)  NULL,
    [DEPL_AVAIL_STATUS_A_EX_D] VARCHAR (50)  NULL,
    [DEPL_AVAIL_STATUS_PHYS]   VARCHAR (50)  NULL,
    [DEPL_AVAIL_STATUS_P_EX_D] VARCHAR (50)  NULL,
    [DEPL_AVAIL_STATUS_LEGAL]  VARCHAR (500) NULL,
    [DEPL_AVAIL_STATUS_L_EX_D] VARCHAR (50)  NULL,
    [DEPL_AVAIL_STATUS_TIME]   VARCHAR (50)  NULL,
    [DEPL_AVAIL_STATUS_T_EX_D] VARCHAR (50)  NULL,
    [PAFSC]                    VARCHAR (50)  NULL,
    [AFSC2]                    VARCHAR (50)  NULL,
    [AFSC3]                    VARCHAR (50)  NULL,
    [SEX_SVC_MBR]              VARCHAR (50)  NULL,
    [DOB]                      VARCHAR (50)  NULL,
    [RET_SEP_EFF_DATE_PROJ]    VARCHAR (50)  NULL,
    [DOS]                      VARCHAR (50)  NULL,
    [SVC_COMP]                 VARCHAR (50)  NULL,
    [TAFCSD]                   VARCHAR (50)  NULL,
    [TAFMSD]                   VARCHAR (50)  NULL,
    [ETS]                      VARCHAR (50)  NULL,
    [LOCAL_ADDR_ZIP]           VARCHAR (50)  NULL,
    [LOCAL_ADDR_STREET_1ST]    VARCHAR (50)  NULL,
    [LOCAL_ADDR_STREET_2ND]    VARCHAR (50)  NULL,
    [CURR_STREET_ADDR_1ST]     VARCHAR (50)  NULL,
    [CURR_STREET_ADDR_2ND]     VARCHAR (50)  NULL,
    [DOR]                      VARCHAR (50)  NULL,
    [DY_EFF_DATE]              VARCHAR (50)  NULL,
    [ETO]                      VARCHAR (50)  NULL,
    [CURR_AERO_RATING]         VARCHAR (50)  NULL,
    [AVN_SVC_CODE]             VARCHAR (50)  NULL,
    [AVN_SVC_CODE_DATE]        VARCHAR (50)  NULL,
    [Gr_Code]                  INT           NULL,
    [PAS_NUMBER]               VARCHAR (4)   NULL,
    [ATTACH_PAS]               VARCHAR (50)  NULL
);
GO

