CREATE TABLE [dbo].[PAL_Data] (
    [LAST_NAME]                     NVARCHAR (30)  NULL,
    [FIRST_NAME]                    NVARCHAR (25)  NULL,
    [SSAN_]                         NVARCHAR (11)  NOT NULL,
    [RANK]                          NVARCHAR (8)   NULL,
    [BIRTH_DATE]                    SMALLDATETIME  NULL,
    [TYPE]                          NVARCHAR (15)  NULL,
    [RATING]                        NVARCHAR (10)  NULL,
    [ASC_CODE]                      NVARCHAR (2)   NULL,
    [BASEASSIGN]                    NVARCHAR (40)  NULL,
    [COMPLETEBY]                    NVARCHAR (25)  NULL,
    [DISPOSITION]                   NVARCHAR (25)  NULL,
    [SENT_TO]                       NVARCHAR (15)  NULL,
    [DATE__OUT]                     SMALLDATETIME  NULL,
    [DATE_REC]                      SMALLDATETIME  NULL,
    [FICHE]                         NVARCHAR (2)   NULL,
    [EXPIREDATE]                    SMALLDATETIME  NULL,
    [Indefinite Waiver]             BIT            NOT NULL,
    [WNLR]                          BIT            NOT NULL,
    [DIAGNOSIS]                     NTEXT          NULL,
    [REMARKS]                       NTEXT          NULL,
    [RWOA]                          BIT            NOT NULL,
    [RWOA REASON]                   NTEXT          NULL,
    [TRWOA]                         BIT            NOT NULL,
    [RECEIVED FROM]                 NVARCHAR (50)  NULL,
    [He/She]                        NVARCHAR (3)   NULL,
    [his/her]                       NVARCHAR (3)   NULL,
    [him/her]                       NVARCHAR (3)   NULL,
    [Ret to Duty by]                NVARCHAR (25)  NULL,
    [ALC-C]                         BIT            NULL,
    [AF FORM 422 (FEB 93 FORMAT)]   BIT            NOT NULL,
    [NARRATIVE SUMMARY]             BIT            NOT NULL,
    [Questionnaire]                 BIT            NOT NULL,
    [UNIT COMMANDER'S Memo]         BIT            NOT NULL,
    [IPEB ELECTION INCLUDED]        BIT            NOT NULL,
    [IPEBElectedYes]                BIT            NOT NULL,
    [IPEBElectedNo]                 BIT            NOT NULL,
    [NoHome]                        BIT            NOT NULL,
    [Asthma/Gen (12)]               BIT            NOT NULL,
    [CAD (12-1)]                    BIT            NOT NULL,
    [DM (12-2)]                     BIT            NOT NULL,
    [HIV (12-3)]                    BIT            NOT NULL,
    [Psych (12-4)]                  BIT            NOT NULL,
    [Home Station - No mandays]     BIT            NOT NULL,
    [CONUS]                         BIT            NOT NULL,
    [CONUS if checked first]        BIT            NOT NULL,
    [1]                             BIT            NOT NULL,
    [3]                             BIT            NOT NULL,
    [3-1]                           BIT            NOT NULL,
    [4]                             BIT            NOT NULL,
    [4-1]                           BIT            NOT NULL,
    [4-1-1]                         BIT            NOT NULL,
    [4-2]                           BIT            NOT NULL,
    [4-3]                           BIT            NOT NULL,
    [4-4]                           BIT            NOT NULL,
    [4-5]                           BIT            NOT NULL,
    [5]                             BIT            NOT NULL,
    [6]                             BIT            NOT NULL,
    [6-1]                           BIT            NOT NULL,
    [7]                             BIT            NOT NULL,
    [8]                             BIT            NOT NULL,
    [9]                             BIT            NOT NULL,
    [9-1]                           BIT            NOT NULL,
    [10]                            BIT            NOT NULL,
    [10-1]                          BIT            NOT NULL,
    [10-2]                          BIT            NOT NULL,
    [10-3]                          BIT            NOT NULL,
    [11]                            BIT            NOT NULL,
    [13]                            BIT            NOT NULL,
    [15]                            BIT            NOT NULL,
    [16]                            BIT            NOT NULL,
    [16-1]                          BIT            NOT NULL,
    [16-2]                          BIT            NOT NULL,
    [16-2-1]                        BIT            NOT NULL,
    [16-3]                          BIT            NOT NULL,
    [16-4]                          BIT            NOT NULL,
    [16-5]                          BIT            NOT NULL,
    [16-5A]                         BIT            NOT NULL,
    [16-6]                          BIT            NOT NULL,
    [16-7]                          BIT            NOT NULL,
    [16-7A]                         BIT            NOT NULL,
    [16-7B]                         BIT            NOT NULL,
    [18]                            BIT            NOT NULL,
    [20]                            BIT            NOT NULL,
    [21]                            BIT            NOT NULL,
    [21-1]                          BIT            NOT NULL,
    [22]                            BIT            NOT NULL,
    [DQ Para Number]                NVARCHAR (100) NULL,
    [DQ Diagnosis]                  NTEXT          NULL,
    [Additional Comments]           NTEXT          NULL,
    [Signature]                     NVARCHAR (200) NULL,
    [Medical Evaluation Fact Sheet] BIT            NOT NULL,
    [ART and DSN]                   NVARCHAR (50)  NULL,
    [Discharged?]                   BIT            NOT NULL,
    [Retired?]                      BIT            NOT NULL,
    [Cancer]                        BIT            NOT NULL,
    [Coronary]                      BIT            NOT NULL,
    [DM]                            BIT            NOT NULL,
    [HIV]                           BIT            NOT NULL,
    [Musculoskeletal]               BIT            NOT NULL,
    [Psych]                         BIT            NOT NULL,
    [Pulmonary]                     BIT            NOT NULL,
    [RK]                            BIT            NOT NULL,
    [Neuro]                         BIT            NOT NULL,
    [Other]                         BIT            NOT NULL,
    [Dental]                        BIT            NOT NULL,
    [GI]                            BIT            NOT NULL,
    [EENT]                          BIT            NOT NULL,
    [He/She(NotCapped)]             NVARCHAR (50)  NULL,
    [DateSentToFiche]               SMALLDATETIME  NULL,
    [Renewal]                       BIT            NOT NULL,
    [ARCHIVE]                       BIT            NOT NULL,
    [RE-ACTIVATE]                   BIT            NULL,
    [Input By]                      NVARCHAR (50)  NULL,
    [RcdId]                         INT            NOT NULL,
    [RetiredDesc]                   NVARCHAR (5)   NULL,
    [DischargedDesc]                NVARCHAR (5)   NULL,
    [Miscellaneous]                 VARCHAR (MAX)  NULL
);
GO

ALTER TABLE [dbo].[PAL_Data]
    ADD CONSTRAINT [PK_PAL_Data] PRIMARY KEY CLUSTERED ([SSAN_] ASC);
GO

