CREATE TABLE [dbo].[PAL_Data_Temp] (
    [ID]                            INT            IDENTITY (1, 1) NOT NULL,
    [LAST_NAME]                     NVARCHAR (30)  NULL,
    [FIRST_NAME]                    NVARCHAR (25)  NULL,
    [SSAN_]                         NVARCHAR (11)  NULL,
    [RANK]                          NVARCHAR (8)   NULL,
    [BIRTH_DATE]                    SMALLDATETIME  NULL,
    [TYPE]                          NVARCHAR (15)  NULL,
    [RATING]                        NVARCHAR (10)  NULL,
    [ASC_CODE]                      NVARCHAR (2)   NULL,
    [BASEASSIGN]                    NVARCHAR (40)  NULL,
    [COMPLETEBY]                    NVARCHAR (25)  NULL,
    [DISPOSITION]                   NVARCHAR (25)  NULL,
    [SENT_TO]                       NVARCHAR (15)  NULL,
    [DATE__OUT]                     SMALLDATETIME  NULL,
    [DATE_REC]                      SMALLDATETIME  NULL,
    [FICHE]                         NVARCHAR (2)   NULL,
    [EXPIREDATE]                    SMALLDATETIME  NULL,
    [Indefinite Waiver]             BIT            NULL,
    [WNLR]                          BIT            NULL,
    [DIAGNOSIS]                     NTEXT          NULL,
    [REMARKS]                       NTEXT          NULL,
    [RWOA]                          BIT            NULL,
    [RWOA REASON]                   NTEXT          NULL,
    [TRWOA]                         BIT            NULL,
    [RECEIVED FROM]                 NVARCHAR (50)  NULL,
    [He/She]                        NVARCHAR (3)   NULL,
    [his/her]                       NVARCHAR (3)   NULL,
    [him/her]                       NVARCHAR (3)   NULL,
    [Ret to Duty by]                NVARCHAR (25)  NULL,
    [ALC-C]                         BIT            NULL,
    [AF FORM 422 (FEB 93 FORMAT)]   BIT            NULL,
    [NARRATIVE SUMMARY]             BIT            NULL,
    [Questionnaire]                 BIT            NULL,
    [UNIT COMMANDER'S Memo]         BIT            NULL,
    [IPEB ELECTION INCLUDED]        BIT            NULL,
    [IPEBElectedYes]                BIT            NULL,
    [IPEBElectedNo]                 BIT            NULL,
    [NoHome]                        BIT            NULL,
    [Asthma/Gen (12)]               BIT            NULL,
    [CAD (12-1)]                    BIT            NULL,
    [DM (12-2)]                     BIT            NULL,
    [HIV (12-3)]                    BIT            NULL,
    [Psych (12-4)]                  BIT            NULL,
    [Home Station - No mandays]     BIT            NULL,
    [CONUS]                         BIT            NULL,
    [CONUS if checked first]        BIT            NULL,
    [1]                             BIT            NULL,
    [3]                             BIT            NULL,
    [3-1]                           BIT            NULL,
    [4]                             BIT            NULL,
    [4-1]                           BIT            NULL,
    [4-1-1]                         BIT            NULL,
    [4-2]                           BIT            NULL,
    [4-3]                           BIT            NULL,
    [4-4]                           BIT            NULL,
    [4-5]                           BIT            NULL,
    [5]                             BIT            NULL,
    [6]                             BIT            NULL,
    [6-1]                           BIT            NULL,
    [7]                             BIT            NULL,
    [8]                             BIT            NULL,
    [9]                             BIT            NULL,
    [9-1]                           BIT            NULL,
    [10]                            BIT            NULL,
    [10-1]                          BIT            NULL,
    [10-2]                          BIT            NULL,
    [10-3]                          BIT            NULL,
    [11]                            BIT            NULL,
    [13]                            BIT            NULL,
    [15]                            BIT            NULL,
    [16]                            BIT            NULL,
    [16-1]                          BIT            NULL,
    [16-2]                          BIT            NULL,
    [16-2-1]                        BIT            NULL,
    [16-3]                          BIT            NULL,
    [16-4]                          BIT            NULL,
    [16-5]                          BIT            NULL,
    [16-5A]                         BIT            NULL,
    [16-6]                          BIT            NULL,
    [16-7]                          BIT            NULL,
    [16-7A]                         BIT            NULL,
    [16-7B]                         BIT            NULL,
    [18]                            BIT            NULL,
    [20]                            BIT            NULL,
    [21]                            BIT            NULL,
    [21-1]                          BIT            NULL,
    [22]                            BIT            NULL,
    [DQ Para Number]                NVARCHAR (100) NULL,
    [DQ Diagnosis]                  NTEXT          NULL,
    [Additional Comments]           NTEXT          NULL,
    [Signature]                     NVARCHAR (200) NULL,
    [Medical Evaluation Fact Sheet] BIT            NULL,
    [ART and DSN]                   NVARCHAR (50)  NULL,
    [Discharged?]                   BIT            NULL,
    [Retired?]                      BIT            NULL,
    [Cancer]                        BIT            NULL,
    [Coronary]                      BIT            NULL,
    [DM]                            BIT            NULL,
    [HIV]                           BIT            NULL,
    [Musculoskeletal]               BIT            NULL,
    [Psych]                         BIT            NULL,
    [Pulmonary]                     BIT            NULL,
    [RK]                            BIT            NULL,
    [Neuro]                         BIT            NULL,
    [Other]                         BIT            NULL,
    [Dental]                        BIT            NULL,
    [GI]                            BIT            NULL,
    [EENT]                          BIT            NULL,
    [He/She(NotCapped)]             NVARCHAR (50)  NULL,
    [DateSentToFiche]               SMALLDATETIME  NULL,
    [Renewal]                       BIT            NULL,
    [ARCHIVE]                       BIT            NULL,
    [RE-ACTIVATE]                   BIT            NULL,
    [Input By]                      NVARCHAR (50)  NULL,
    [RcdId]                         INT            NULL,
    [RetiredDesc]                   NVARCHAR (5)   NULL,
    [DischargedDesc]                NVARCHAR (5)   NULL,
    [Imported]                      BIT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);
GO

