CREATE TABLE [dbo].[tmp_command_struct] (
    [CS_ID]                 INT            NULL,
    [UIC]                   VARCHAR (4000) NULL,
    [UNIT_NBR]              VARCHAR (4000) NULL,
    [UNIT_KIND]             VARCHAR (4000) NULL,
    [UNIT_TYPE]             VARCHAR (4000) NULL,
    [UNIT_DET]              VARCHAR (4000) NULL,
    [LONG_NAME]             VARCHAR (4000) NULL,
    [CS_ID_PARENT]          INT            NULL,
    [CS_OPER_TYPE]          VARCHAR (4000) NULL,
    [CS_LEVEL]              VARCHAR (4000) NULL,
    [PAS_CODE]              VARCHAR (4000) NULL,
    [ADDRESS1]              VARCHAR (4000) NULL,
    [ADDRESS2]              VARCHAR (4000) NULL,
    [CITY]                  VARCHAR (4000) NULL,
    [STATE]                 VARCHAR (4000) NULL,
    [POSTAL_CODE]           VARCHAR (4000) NULL,
    [COUNTRY]               VARCHAR (4000) NULL,
    [E_MAIL]                VARCHAR (4000) NULL,
    [COMPONENT]             VARCHAR (4000) NULL,
    [COMMAND_CODE]          VARCHAR (4000) NULL,
    [GAINING_COMMAND_CS_ID] INT            NULL,
    [MRDSS_DOC_ID]          VARCHAR (4000) NULL,
    [MRDSS_DOC_DATE]        VARCHAR (4000) NULL,
    [MRDSS_DOC_REVIEW]      VARCHAR (4000) NULL,
    [MRDSS_KIND]            VARCHAR (4000) NULL,
    [MEDICAL_SERVICE]       VARCHAR (4000) NULL,
    [CREATED_BY]            VARCHAR (4000) NULL,
    [CREATED_DATE]          DATETIME       NULL,
    [MODIFIED_BY]           VARCHAR (4000) NULL,
    [MODIFIED_DATE]         DATETIME       NULL,
    [COMMAND_STRUCT_UTC]    VARCHAR (4000) NULL,
    [GEO_LOC]               VARCHAR (4000) NULL,
    [BASE_CODE]             VARCHAR (4000) NULL,
    [PHYS_EXAM_YN]          VARCHAR (4000) NULL,
    [SCHEDULING_YN]         VARCHAR (4000) NULL,
    [TIME_ZONE]             VARCHAR (4000) NULL
);
GO

