CREATE TABLE [dbo].[tmp_rg_xx_Command_Struct] (
    [CS_ID]                 INT            IDENTITY (0, 1) NOT NULL,
    [ADDRESS1]              NVARCHAR (100) NULL,
    [ADDRESS2]              NVARCHAR (100) NULL,
    [BASE_CODE]             NVARCHAR (2)   NULL,
    [CITY]                  NVARCHAR (30)  NULL,
    [COMMAND_CODE]          NVARCHAR (2)   NULL,
    [COMMAND_STRUCT_UTC]    NVARCHAR (5)   NULL,
    [COMPONENT]             NVARCHAR (4)   NULL,
    [COUNTRY]               NVARCHAR (40)  NULL,
    [CREATED_BY]            NVARCHAR (30)  NULL,
    [CREATED_DATE]          DATETIME       NULL,
    [CS_ID_PARENT]          INT            NULL,
    [CS_LEVEL]              NVARCHAR (10)  NULL,
    [CS_OPER_TYPE]          NVARCHAR (2)   NULL,
    [E_MAIL]                NVARCHAR (40)  NULL,
    [GAINING_COMMAND_CS_ID] INT            NULL,
    [GEO_LOC]               NVARCHAR (4)   NULL,
    [LONG_NAME]             NVARCHAR (100) NULL,
    [MEDICAL_SERVICE]       NVARCHAR (4)   NULL,
    [MODIFIED_BY]           NVARCHAR (30)  NULL,
    [MODIFIED_DATE]         DATETIME       NULL,
    [MRDSS_DOC_DATE]        DATETIME       NULL,
    [MRDSS_DOC_ID]          NVARCHAR (4)   NULL,
    [MRDSS_DOC_REVIEW]      NVARCHAR (24)  NULL,
    [MRDSS_KIND]            NVARCHAR (4)   NULL,
    [PAS_CODE]              VARCHAR (4)    NULL,
    [PHYS_EXAM_YN]          NVARCHAR (1)   NULL,
    [POSTAL_CODE]           NVARCHAR (10)  NULL,
    [SCHEDULING_YN]         NVARCHAR (1)   NULL,
    [STATE]                 NVARCHAR (2)   NULL,
    [TIME_ZONE]             NVARCHAR (3)   NULL,
    [UIC]                   NVARCHAR (6)   NULL,
    [UNIT_DET]              NVARCHAR (4)   NULL,
    [UNIT_KIND]             NVARCHAR (5)   NULL,
    [UNIT_NBR]              NVARCHAR (4)   NULL,
    [UNIT_TYPE]             NVARCHAR (2)   NULL
);
GO

