// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class ApplicationWarmupProcess_sp_GetAllLogsResult
    {
        public int Id { get; set; }
        [StringLength(100)]
        public string Name { get; set; } = default!;
        public DateTime ExecutionDate { get; set; }
        [StringLength(2147483647)]
        public string? Message { get; set; }
    }