// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    /// <summary>
    /// Result type for the total count returned by the ApplicationWarmupProcess_sp_GetAllLogs_pagination stored procedure.
    /// </summary>
    public partial class ApplicationWarmupProcess_sp_GetAllLogs_pagination_TotalCountResult
    {
        /// <summary>
        /// Gets or sets the total count of records matching the filter criteria.
        /// </summary>
        public int TotalCount { get; set; }
    }