// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class arcnet_GetIAATrainingDataForUsersResult
    {
        public int? UserId { get; set; }
        [StringLength(100)]
        public string? EDIPIN { get; set; }
        public string? SSN { get; set; }
        [StringLength(100)]
        public string? Username { get; set; }
        [StringLength(500)]
        public string? Name { get; set; }
        [StringLength(100)]
        public string? ECT_IAAExpirationDate { get; set; }
        [StringLength(100)]
        public string? ARCNET_IAACompletionDate { get; set; }
        [StringLength(100)]
        public string? ARCNET_IAAExpirationDate { get; set; }
    }