// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class arcnet_GetLastExecutionDateResult
    {
        public DateTime? LastExecutionDate { get; set; }
    }