// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class cmdStruct_sp_GetUnitIdResult
    {
        public int CS_ID { get; set; }
    }