// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_pascodes_GetParentChainResult
    {
        public int cs_id { get; set; }
        [StringLength(100)]
        public string? ParentName { get; set; }
        [StringLength(4)]
        public string? parentPasCode { get; set; }
        public int? view_type { get; set; }
        public int Level { get; set; }
        public int? userUnit { get; set; }
    }