// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_tracking_sp_GetByUserIdResult
    {
        public DateTime actionDate { get; set; }
        [StringLength(50)]
        public string? description { get; set; }
        [StringLength(50)]
        public string actionName { get; set; } = default!;
        [StringLength(1000)]
        public string? notes { get; set; }
        [StringLength(100)]
        public string lastname { get; set; } = default!;
        public byte actionId { get; set; }
        public int logId { get; set; }
        public int userId { get; set; }
        public bool? logChanges { get; set; }
        public byte moduleId { get; set; }
        [StringLength(50)]
        public string moduleName { get; set; } = default!;
        public int? referenceId { get; set; }
        [StringLength(50)]
        public string? caseId { get; set; }
    }