// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_APSA_sp_GetPostCompletionResult
    {
        public int appeal_id { get; set; }
        [StringLength(200)]
        public string? appeal_street { get; set; }
        [StringLength(100)]
        public string? appeal_city { get; set; }
        [StringLength(50)]
        public string? appeal_state { get; set; }
        [StringLength(100)]
        public string? appeal_zip { get; set; }
        [StringLength(50)]
        public string? appeal_country { get; set; }
        public DateOnly? member_notification_date { get; set; }
        [StringLength(50)]
        public string? helpExtensionNumber { get; set; }
        [StringLength(200)]
        public string? email { get; set; }
    }