// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_Signature_sp_GetResult
    {
        public int refId { get; set; }
        public int workflow { get; set; }
        [StringLength(2147483647)]
        public string signature { get; set; } = default!;
        [StringLength(2147483647)]
        public string sig_date { get; set; } = default!;
        public int? user_id { get; set; }
        public int? ptype { get; set; }
    }