// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_Workflow_sp_GetPermissionsByCompoResult
    {
        public byte groupId { get; set; }
        [StringLength(100)]
        public string name { get; set; } = default!;
        public bool? canView { get; set; }
        public bool? canCreate { get; set; }
    }