// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_permissions_sp_GetGroupPermissionsResult
    {
        public short permid { get; set; }
        [StringLength(50)]
        public string permName { get; set; } = default!;
        [StringLength(100)]
        public string permDesc { get; set; } = default!;
        public bool? Allowed { get; set; }
        public bool exclude { get; set; }
        public short? GroupId { get; set; }
    }