// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_lookUps_sp_GetMemberPSCDCategoryResult
    {
        public int serviceID { get; set; }
        [StringLength(100)]
        public string? service { get; set; }
    }