// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_group_sp_GetManagedResult
    {
        public byte? groupId { get; set; }
        [StringLength(100)]
        public string? name { get; set; }
        public bool? notify { get; set; }
        public bool? ViewBy { get; set; }
    }