// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_workflow_sp_GetFindingsResult
    {
        public byte? Id { get; set; }
        [StringLength(50)]
        public string? FindingType { get; set; }
        [StringLength(100)]
        public string? Description { get; set; }
    }