// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_lookUps_sp_DutyStatusesResult
    {
        [StringLength(50)]
        public string Description { get; set; } = default!;
        [StringLength(50)]
        public string? Type { get; set; }
        public int? sort_order { get; set; }
        public byte id { get; set; }
    }