// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_pascode_sp_searchResult
    {
        public int CS_ID { get; set; }
        [StringLength(106)]
        public string? LONG_NAME { get; set; }
        [StringLength(4)]
        public string? PAS_CODE { get; set; }
    }