// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_lod_sp_GetCompletedSpecialCasesByMemberSSNResult
    {
        public int RefId { get; set; }
        [StringLength(4)]
        public string? Protected_SSN { get; set; }
        [StringLength(100)]
        public string Member_Name { get; set; } = default!;
        [StringLength(100)]
        public string Unit_Name { get; set; } = default!;
        [StringLength(50)]
        public string Case_Id { get; set; } = default!;
        [StringLength(50)]
        public string Status { get; set; } = default!;
        public byte Module_Id { get; set; }
        [StringLength(50)]
        public string Module { get; set; } = default!;
        public string? ReceiveDate { get; set; }
        public int? Days { get; set; }
    }