// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_lookUps_sp_RMUNamesResult
    {
        public int Value { get; set; }
        [StringLength(255)]
        public string? Name { get; set; }
        [StringLength(4)]
        public string? PAS { get; set; }
        public bool Collocated { get; set; }
    }