// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_user_sp_GetMailingListByStatus_SCResult
    {
        [StringLength(200)]
        public string? Email { get; set; }
    }