// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_messages_sp_GetAllMessagesResult
    {
        public short messageId { get; set; }
        [StringLength(50)]
        public string? title { get; set; }
        public DateTime startTime { get; set; }
        public DateTime? endTime { get; set; }
        public bool popup { get; set; }
        public bool isAdminMessage { get; set; }
    }