// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_permissions_sp_GetAllPendingRequestsResult
    {
        public int userID { get; set; }
        [StringLength(100)]
        public string LastName { get; set; } = default!;
        [StringLength(100)]
        public string FirstName { get; set; } = default!;
        [StringLength(4)]
        public string? SSN { get; set; }
        [Column("Unit Name")]
        [StringLength(100)]
        public string? UnitName { get; set; }
        [Column("Pas Code")]
        [StringLength(4)]
        public string? PasCode { get; set; }
        [Column("Date Requested")]
        public DateTime DateRequested { get; set; }
        public bool NewRole { get; set; }
        [Column("Group Name")]
        [StringLength(100)]
        public string GroupName { get; set; } = default!;
    }