// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_log_sp_GetErrorsResult
    {
        public int logId { get; set; }
        public DateTime errorTime { get; set; }
        [StringLength(50)]
        public string? userName { get; set; }
        [StringLength(200)]
        public string? page { get; set; }
        [StringLength(2147483647)]
        public string? message { get; set; }
    }