// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_lod_sp_GetCaseCommentsResult
    {
        public int LodId { get; set; }
        public DateTime created_date { get; set; }
        public int created_by { get; set; }
        [StringLength(2147483647)]
        public string comments { get; set; } = default!;
    }