// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_lookups_sp_GetAvailabilityCodeResult
    {
        public int availabilityCode { get; set; }
        [StringLength(50)]
        public string description { get; set; } = default!;
    }