// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_lookUps_sp_OccurrencesResult
    {
        [StringLength(100)]
        public string description { get; set; } = default!;
        public int id { get; set; }
        public int sort_order { get; set; }
    }