// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_pascode_sp_LoadResult
    {
        public int CS_ID { get; set; }
        [StringLength(100)]
        public string? LONG_NAME { get; set; }
        [StringLength(4)]
        public string? UNIT_NBR { get; set; }
        [StringLength(5)]
        public string? UNIT_KIND { get; set; }
        [StringLength(2)]
        public string? UNIT_TYPE { get; set; }
        [StringLength(4)]
        public string? UNIT_DET { get; set; }
        [StringLength(6)]
        public string? UIC { get; set; }
        [StringLength(10)]
        public string? CS_LEVEL { get; set; }
        public int? CS_ID_PARENT { get; set; }
        public int? GAINING_COMMAND_CS_ID { get; set; }
        [StringLength(4)]
        public string? PAS_CODE { get; set; }
        [StringLength(10)]
        public string? BASE_CODE { get; set; }
        [StringLength(2)]
        public string? CS_OPER_TYPE { get; set; }
        [StringLength(3)]
        public string? TIME_ZONE { get; set; }
        [StringLength(4)]
        public string? COMPONENT { get; set; }
        [StringLength(10)]
        public string? GEO_LOC { get; set; }
        [StringLength(1)]
        public string? PHYS_EXAM_YN { get; set; }
        [StringLength(1)]
        public string? SCHEDULING_YN { get; set; }
        [StringLength(100)]
        public string? ADDRESS1 { get; set; }
        [StringLength(100)]
        public string? ADDRESS2 { get; set; }
        [StringLength(30)]
        public string? CITY { get; set; }
        [StringLength(40)]
        public string? COUNTRY { get; set; }
        [StringLength(2)]
        public string? STATE { get; set; }
        [StringLength(20)]
        public string? POSTAL_CODE { get; set; }
        [StringLength(40)]
        public string? E_MAIL { get; set; }
    }