// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_user_sp_GetMailingListByUserResult
    {
        public int UserId { get; set; }
        [StringLength(15)]
        public string? Rank { get; set; }
        [StringLength(100)]
        public string FirstName { get; set; } = default!;
        [StringLength(100)]
        public string LastName { get; set; } = default!;
        [StringLength(200)]
        public string? Email { get; set; }
    }