// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_role_sp_GetAllResult
    {
        public int userRoleId { get; set; }
        public byte groupId { get; set; }
        [StringLength(100)]
        public string name { get; set; } = default!;
        [StringLength(10)]
        public string abbr { get; set; } = default!;
        public byte status { get; set; }
        public byte accessScope { get; set; }
    }