// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_lookUps_sp_GetGradeAbbreviationByTypeAndCodeResult
    {
        [StringLength(25)]
        public string Abbreviation { get; set; } = default!;
    }