// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_CaseComments_GetByCaseResult
    {
        public int id { get; set; }
        public int lodid { get; set; }
        [StringLength(2147483647)]
        public string comments { get; set; } = default!;
        public int created_by { get; set; }
        public DateTime created_date { get; set; }
        public bool deleted { get; set; }
        public int ModuleID { get; set; }
        public int CommentType { get; set; }
    }