// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_permissions_sp_GetByUserIdResult
    {
        public short? permId { get; set; }
        [StringLength(50)]
        public string? permName { get; set; }
        [StringLength(100)]
        public string? permDesc { get; set; }
        public bool? allowed { get; set; }
        public bool? exclude { get; set; }
    }