// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_sc_sp_GetRWAssociableSpecialCasesResult
    {
        public int RefId { get; set; }
        [StringLength(50)]
        public string CaseId { get; set; } = default!;
        [StringLength(50)]
        public string moduleName { get; set; } = default!;
    }