// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_email_sp_GetEmailByIDResult
    {
        public int TemplateID { get; set; }
        [StringLength(100)]
        public string Subject { get; set; } = default!;
        [StringLength(2000)]
        public string Body { get; set; } = default!;
        [StringLength(100)]
        public string Title { get; set; } = default!;
        [StringLength(50)]
        public string? DataProc { get; set; }
        public bool active { get; set; }
    }