// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_workflow_sp_GetPageAccessByWorkflowViewResult
    {
        public short PageId { get; set; }
        public byte GroupId { get; set; }
        public byte? Access { get; set; }
        public byte? WorkflowId { get; set; }
        public int? WorkStatusId { get; set; }
        [StringLength(50)]
        public string PageTitle { get; set; } = default!;
    }