// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_user_sp_GetManagedUsersResult
    {
        public int Id { get; set; }
        public byte Status { get; set; }
        [StringLength(4)]
        public string? LastFour { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; } = default!;
        [StringLength(50)]
        public string LastName { get; set; } = default!;
        [StringLength(50)]
        public string? RANK { get; set; }
        [StringLength(50)]
        public string? GRADE { get; set; }
        public DateTime expirationDate { get; set; }
        [StringLength(50)]
        public string RoleName { get; set; } = default!;
        [StringLength(100)]
        public string? CurrentUnitName { get; set; }
        [StringLength(50)]
        public string AccessStatusText { get; set; } = default!;
        [StringLength(50)]
        public string username { get; set; } = default!;
        public string workCompo { get; set; } = default!;
        public byte GroupId { get; set; }
        public int? ViewOrManaged { get; set; }
    }