// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_lod_sp_GetLODListByMemberSSNResult
    {
        public int refId { get; set; }
        [StringLength(50)]
        public string caseId { get; set; } = default!;
        public byte workflowId { get; set; }
    }