// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_messages_sp_GetMessagesGroupsResult
    {
        public byte groupID { get; set; }
        [StringLength(100)]
        public string name { get; set; } = default!;
        public int assigned { get; set; }
    }