// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_ICD_sp_GetChildrenResult
    {
        public int ICD9_ID { get; set; }
        [StringLength(7)]
        public string? value { get; set; }
        [StringLength(250)]
        public string? text { get; set; }
        public bool isDisease { get; set; }
        public bool Active { get; set; }
    }