// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_lookUps_sp_GetPasCodeChainTypeResult
    {
        public byte Value { get; set; }
        [StringLength(100)]
        public string? Name { get; set; }
    }