// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_Signature_sp_GetByIdResult
    {
        public int? Id { get; set; }
        public string? SignatureName { get; set; }
        public string? SignatureDescription { get; set; }
        public string? SignatureData { get; set; }
        public int? WorkflowId { get; set; }
        public int? UserId { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }