// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_CertificationStamp_sp_GetWorkflowCertificationStampsResult
    {
        public int Id { get; set; }
        [StringLength(100)]
        public string Name { get; set; } = default!;
        [StringLength(500)]
        public string Body { get; set; } = default!;
        public bool IsQualified { get; set; }
    }