// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class core_memo_sp_GetUserGroupsByTemplateIdResult
    {
        public byte groupId { get; set; }
        [StringLength(100)]
        public string name { get; set; } = default!;
        public bool canEdit { get; set; }
        public bool canCreate { get; set; }
        public bool canView { get; set; }
        public bool canDelete { get; set; }
    }