// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class Form348_Audit_GetAuditInfoResult
    {
        public int LOD_ID { get; set; }
        [StringLength(50)]
        public string CaseID { get; set; } = default!;
        public int Workflow { get; set; }
        public short? MedicallyAppropriate { get; set; }
        public bool? SG_DX { get; set; }
        public bool? SG_ISupport { get; set; }
        public bool? SG_EPTS { get; set; }
        public bool? SG_Aggravation { get; set; }
        public bool? SG_Principles { get; set; }
        [StringLength(1000)]
        public string? SG_Other { get; set; }
        public short? SG_ProofApplied { get; set; }
        public short? SG_CorrectStandard { get; set; }
        public short? SG_ProofMet { get; set; }
        public short? SG_Evidence { get; set; }
        public short? SG_Misconduct { get; set; }
        public short? SG_FormalInvestigation { get; set; }
        public short? LegallySufficient { get; set; }
        public bool? JA_StandardOfProof { get; set; }
        public bool? JA_DeathAndMVA { get; set; }
        public bool? JA_FormalPolicy { get; set; }
        public bool? JA_AFI { get; set; }
        [StringLength(1000)]
        public string? JA_Other { get; set; }
        public short? JA_ProofApplied { get; set; }
        public short? JA_CorrectStandard { get; set; }
        public short? JA_ProofMet { get; set; }
        public short? JA_Evidence { get; set; }
        public short? JA_Misconduct { get; set; }
        public short? JA_FormalInvestigation { get; set; }
        public short? StatusValidated { get; set; }
        public bool? StatusOfMember { get; set; }
        public bool? Orders { get; set; }
        public bool? A1_EPTS { get; set; }
        public bool? IDT { get; set; }
        public bool? PCARS { get; set; }
        public bool? EightYearRule { get; set; }
        [StringLength(1000)]
        public string? A1_Other { get; set; }
        public short? LODInitiation { get; set; }
        public short? WrittenDiagnosis { get; set; }
        public short? MemberRequest { get; set; }
        public short? IncurredOrAggravated { get; set; }
        public short? IllnessOrDisease { get; set; }
        public int? Activites { get; set; }
        [StringLength(2147483647)]
        public string? A1_Comment { get; set; }
        [StringLength(2147483647)]
        public string? JA_Comment { get; set; }
        [StringLength(2147483647)]
        public string? SG_Comment { get; set; }
        public int? Determination { get; set; }
        public int? A1_DeterminationNotCorrect { get; set; }
    }