// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class form348_sp_PostCompletionSearch_TEMPResult
    {
        public int lodid { get; set; }
        [StringLength(4)]
        public string? Protected_SSN { get; set; }
        [StringLength(100)]
        public string? Member_Name { get; set; }
        [StringLength(100)]
        public string? Unit_Name { get; set; }
        [StringLength(50)]
        public string? Case_Id { get; set; }
        [StringLength(50)]
        public string? Status { get; set; }
        [StringLength(50)]
        public string? Module { get; set; }
        public string? Receive_Date { get; set; }
        public int? Days { get; set; }
    }