// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class form348_SC_sp_GroupSearchResult
    {
        public int RefId { get; set; }
        [StringLength(50)]
        public string CaseId { get; set; } = default!;
        [StringLength(100)]
        public string Name { get; set; } = default!;
        [StringLength(4)]
        public string? SSN { get; set; }
        public int Compo { get; set; }
        [StringLength(4)]
        public string? Pascode { get; set; }
        public int WorkStatusId { get; set; }
        [StringLength(50)]
        public string WorkStatus { get; set; } = default!;
        public bool IsFinal { get; set; }
        public byte WorkflowId { get; set; }
        [StringLength(50)]
        public string Workflow { get; set; } = default!;
        public byte ModuleId { get; set; }
        public string? DateCreated { get; set; }
        [StringLength(100)]
        public string? UnitName { get; set; }
        public string? ReceiveDate { get; set; }
        public int? Days { get; set; }
        public int lockId { get; set; }
        [StringLength(62)]
        public string? PrintId { get; set; }
        public int? Sub_Type { get; set; }
        public int? pas_priority { get; set; }
    }