// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class form348_sp_PilotCaseSearchResult
    {
        public int? RefId { get; set; }
        [StringLength(50)]
        public string? CaseId { get; set; }
        [StringLength(100)]
        public string? Name { get; set; }
        [StringLength(2)]
        public string? State { get; set; }
        [StringLength(4)]
        public string? SSN { get; set; }
        public string? Compo { get; set; }
        [StringLength(4)]
        public string? Pascode { get; set; }
        public int? WorkStatusId { get; set; }
        [StringLength(50)]
        public string Description { get; set; } = default!;
        public bool IsFinal { get; set; }
        public byte? WorkflowId { get; set; }
        [StringLength(50)]
        public string Workflow { get; set; } = default!;
        public byte ModuleId { get; set; }
        public bool? IsFormal { get; set; }
        public string? DateCreated { get; set; }
        [StringLength(100)]
        public string? UnitName { get; set; }
        public string? ReceiveDate { get; set; }
        public string? CompletionDate { get; set; }
        public string? actionDate { get; set; }
        [StringLength(1000)]
        public string? notes { get; set; }
        public int? Days { get; set; }
        public int lockId { get; set; }
        [StringLength(3)]
        public string PriorityRank { get; set; } = default!;
    }