// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class form348_SC_sp_PropertiesResult
    {
        public DateTime? Suspense_Date { get; set; }
        [StringLength(50)]
        public string TMT_Number { get; set; } = default!;
        public DateTime? TMT_Receive_Date { get; set; }
        public int? Has_Admin_LOD { get; set; }
        [StringLength(1200)]
        public string? Case_Comments { get; set; }
    }