// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class form348_sp_GetReinvestigationByInitLODResult
    {
        public int InitialLodId { get; set; }
        public int? ReinvestigationLodId { get; set; }
        public int CreatedBy { get; set; }
        public DateOnly CreatedDate { get; set; }
    }