// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class Form348_SC_sp_GetPEPPTypesResult
    {
        public int Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; } = default!;
    }