// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class Form261_sp_Investigation_OtherPeronnelSelectResult
    {
        [StringLength(9)]
        public string? ssn { get; set; }
        [StringLength(100)]
        public string? name { get; set; }
        [StringLength(6)]
        public string? grade { get; set; }
        public string? compo { get; set; }
        public string? investigationDone { get; set; }
    }