// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class GetNumbersInQueue_DailyResult
    {
        [Column("Start Date")]
        public DateTime? StartDate { get; set; }
        [Column("End Date")]
        public DateTime? EndDate { get; set; }
    }