// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class GetStatusOfCurrentWeek_SGCasesResult
    {
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
    }