// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class member_sp_GetSystemAdminChangeHistoryBySSNResult
    {
        public int LogId { get; set; }
        public DateTime ChangeDate { get; set; }
        [StringLength(8)]
        public string ChangeType { get; set; } = default!;
        public int ModifiedByUserId { get; set; }
        [StringLength(100)]
        public string ModifiedByUsername { get; set; } = default!;
        [StringLength(50)]
        public string ModifiedField { get; set; } = default!;
        [StringLength(1000)]
        public string OldValue { get; set; } = default!;
        [StringLength(1000)]
        public string NewValue { get; set; } = default!;
    }