// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class member_sp_findBySSNResult
    {
        [StringLength(11)]
        public string SSN { get; set; } = default!;
        [StringLength(50)]
        public string? FIRST_NAME { get; set; }
        [StringLength(50)]
        public string? LAST_NAME { get; set; }
        [StringLength(60)]
        public string? MIDDLE_NAMES { get; set; }
        [StringLength(4)]
        public string? UNIT_CODE { get; set; }
        [StringLength(1)]
        public string? COMPO { get; set; }
        public int GRCODE { get; set; }
        [StringLength(15)]
        public string? RANK { get; set; }
        [StringLength(50)]
        public string? GRADE { get; set; }
        public DateTime? DOB { get; set; }
        [StringLength(100)]
        public string? UNIT_NAME { get; set; }
        public int UNIT_ID { get; set; }
        [StringLength(50)]
        public string Compo_Descr { get; set; } = default!;
        [StringLength(30)]
        public string? RANK_TITLE { get; set; }
    }