// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class member_sp_GetMembersByNameResult
    {
        [StringLength(50)]
        public string? LastName { get; set; }
        [StringLength(50)]
        public string? FirstName { get; set; }
        [StringLength(60)]
        public string? MiddleName { get; set; }
        [StringLength(11)]
        public string SSN { get; set; } = default!;
        [StringLength(15)]
        public string? Rank { get; set; }
        [StringLength(100)]
        public string? Unit { get; set; }
    }