// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class memo_sp_Lod_Determination_NILOD_InformalResult
    {
        [StringLength(100)]
        public string? id { get; set; }
        [StringLength(2147483647)]
        public string? value { get; set; }
    }