// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class PH_Field_sp_GetAllResult
    {
        public int Id { get; set; }
        [StringLength(100)]
        public string Name { get; set; } = default!;
    }