// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class PH_Workflow_sp_GetCasesByWingRMUResult
    {
        public int RefId { get; set; }
        [StringLength(50)]
        public string Case_Id { get; set; } = default!;
        public byte Module_Id { get; set; }
        [StringLength(50)]
        public string Status { get; set; } = default!;
        public DateTime Created_Date { get; set; }
        public string? Completed_Date { get; set; }
        [StringLength(61)]
        public string? Reporting_Period { get; set; }
    }