// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class PH_Workflow_sp_GetSevenDayWarningEmailsResult
    {
        [StringLength(200)]
        public string? emailAddress { get; set; }
    }