// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class RecentlyAddedDocs_sp_GetByIdsResult
    {
        public long? DocId { get; set; }
        public int? DocTypeId { get; set; }
    }