// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class ReminderEmailGetSettingsByStatusResult
    {
        public int id { get; set; }
        public byte groupId { get; set; }
        [StringLength(100)]
        public string groupName { get; set; } = default!;
        public int templateID { get; set; }
        [StringLength(100)]
        public string templateName { get; set; } = default!;
        public int intervalTime { get; set; }
    }