// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class ReminderGetInactiveSettingsResult
    {
        public int i_id { get; set; }
        public int interval { get; set; }
        public int notification_interval { get; set; }
        public int templateId { get; set; }
        public bool? active { get; set; }
    }