// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class report_sp_LODCompliance_TimelinessResult
    {
        public int? UnitId { get; set; }
        [StringLength(100)]
        public string? MemberUnit { get; set; }
        public int ParentUnitId { get; set; }
        [StringLength(100)]
        public string? ParentMemberUnit { get; set; }
        public int? DaysOpen { get; set; }
        public int? MedTechDays { get; set; }
        public int? MedOffDays { get; set; }
        public int? UnitCCDays { get; set; }
        public int? WingJADays { get; set; }
        public int? WingCCDays { get; set; }
        public int? WingSARCDays { get; set; }
        public int? PMDAys { get; set; }
        public int? IODays { get; set; }
        public int? FormalWingJADays { get; set; }
        public int? FormalWingCCDays { get; set; }
        public int? BoardTechDays { get; set; }
        public int? BoardJADays { get; set; }
        public int? BoardAdminDays { get; set; }
        public int? BoardMedOffDays { get; set; }
        public int? ApprAuthDays { get; set; }
        public int? FormalBoardTechDays { get; set; }
        public int? FormalBoardJADays { get; set; }
        public int? FormalBoardAdminDays { get; set; }
        public int? FormalBoardMedOffDays { get; set; }
        public int? FormalApprAuthDays { get; set; }
    }