// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.ResultTypes;

public partial class ReportStoredResult
{
    public int UserId { get; set; }

    public string ReportTitle { get; set; } = null!;

    public string ResultData { get; set; } = null!;
}
