// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class report_sp_LODSARCCasesResult
    {
        public int? RefId { get; set; }
        public byte? ModuleId { get; set; }
        public byte? WorkflowId { get; set; }
        [StringLength(100)]
        public string? CaseId { get; set; }
        public bool? IsRestricted { get; set; }
        public bool? IsComplete { get; set; }
        public int? WorkStatusId { get; set; }
        [StringLength(50)]
        public string? StatusCodeName { get; set; }
        [StringLength(100)]
        public string? MemberUnit { get; set; }
        public int? MemberUnitId { get; set; }
        [StringLength(100)]
        public string? MemberName { get; set; }
        [StringLength(9)]
        public string? MemberSSN { get; set; }
    }