// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class report_sp_PHTotalsStringValuesReportResult
    {
        [Column("PH Wing RMU")]
        [StringLength(100)]
        public string? PHWingRMU { get; set; }
        public string? RawReportingPeriod { get; set; }
        [Column("Reporting Period")]
        [StringLength(61)]
        public string? ReportingPeriod { get; set; }
        public int SectionId { get; set; }
        public int FieldId { get; set; }
        public int FieldTypeId { get; set; }
        [Column("Section Name")]
        [StringLength(100)]
        public string SectionName { get; set; } = default!;
        [Column("Field Name")]
        [StringLength(100)]
        public string FieldName { get; set; } = default!;
        [StringLength(1000)]
        public string Value { get; set; } = default!;
    }