// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class report_pkgLogResult
    {
        public DateTime? starttime { get; set; }
        public DateTime? endtime { get; set; }
        [StringLength(50)]
        public string? pkgName { get; set; }
        public int? nRowRawInserted { get; set; }
        public int? nRowInserted { get; set; }
        public int? nRowUpdated { get; set; }
        public int? nModifiedRecords { get; set; }
        public int? nDeletedMembers { get; set; }
    }