// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class report_sp_GetDetailLodByUnitIdResult
    {
        public int lodid { get; set; }
        public int member_unit_id { get; set; }
        [StringLength(50)]
        public string case_id { get; set; } = default!;
        [StringLength(100)]
        public string member_unit { get; set; } = default!;
        [StringLength(100)]
        public string? event_nature_type { get; set; }
        [StringLength(50)]
        public string? description { get; set; }
        public int? icd9Id { get; set; }
        [StringLength(250)]
        public string? icdName { get; set; }
    }