// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class report_sp_GetSpecialCasesRFAByGroupResult
    {
        [StringLength(100)]
        public string? Unit { get; set; }
        [StringLength(4)]
        public string? PAS { get; set; }
        [StringLength(100)]
        public string? CaseId { get; set; }
        public DateTime? DateSent { get; set; }
        [StringLength(150)]
        public string? ReasonSentBack { get; set; }
        [StringLength(2147483647)]
        public string? ExplanationForSendingBack { get; set; }
    }