// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class report_sp_LODActivityResult
    {
        public int lodid { get; set; }
        [StringLength(50)]
        public string case_id { get; set; } = default!;
        [StringLength(100)]
        public string Name { get; set; } = default!;
        [StringLength(4)]
        public string? SSN { get; set; }
        [StringLength(100)]
        public string member_unit { get; set; } = default!;
        public int cs_id { get; set; }
        [StringLength(50)]
        public string? description { get; set; }
    }