// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class report_sp_LODComplianceResult
    {
        public int? lodId { get; set; }
    }