// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class report_sp_PHTotalsSuicideMethodsReportResult
    {
        public int RefId { get; set; }
        public int SectionId { get; set; }
        public int FieldId { get; set; }
        public int FieldTypeId { get; set; }
        [StringLength(1000)]
        public string Value { get; set; } = default!;
    }