// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class report_OpenStatusCountResult
    {
        public int? cs_id { get; set; }
        public string? pas { get; set; }
        public int? viewType { get; set; }
        [StringLength(200)]
        public string? name { get; set; }
        public int medical { get; set; }
        public int unit { get; set; }
        public int wingja { get; set; }
        public int wingcc { get; set; }
        public int lodPM { get; set; }
        public int formalInvestigation { get; set; }
        public int formalActionWingJA { get; set; }
        public int formalActionWingCC { get; set; }
        public int? LodBoard { get; set; }
        public int ApprovingAuthority { get; set; }
        public int formalInvestigationDirected { get; set; }
        public int? Total { get; set; }
    }