// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class SearchDBForStringResult
    {
        [StringLength(128)]
        public string SchemaName { get; set; } = default!;
        [StringLength(128)]
        public string TableName { get; set; } = default!;
        [StringLength(128)]
        public string ColumnName { get; set; } = default!;
    }