// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class SpecialCaseRFAResult
    {
        [StringLength(100)]
        public string? Unit { get; set; }
        [StringLength(4)]
        public string? PAS { get; set; }
        [Column("Total Cases")]
        public int? TotalCases { get; set; }
        [Column("Total Cases With No RWOAs")]
        public int? TotalCasesWithNoRWOAs { get; set; }
        [Column("Total Cases With RWOAs")]
        public int? TotalCasesWithRWOAs { get; set; }
        [Column("Total Cases With One RWOA")]
        public int? TotalCasesWithOneRWOA { get; set; }
        [Column("Total Cases With More Than One RWOA")]
        public int? TotalCasesWithMoreThanOneRWOA { get; set; }
        [Column("Total RWOAs")]
        public int? TotalRWOAs { get; set; }
        [StringLength(2147483647)]
        public string? Reasons { get; set; }
    }