// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class tmp_report_sp_GetDispositionResult
    {
        public int? DispositionId { get; set; }
        [StringLength(100)]
        public string? DispositionName { get; set; }
        public int? CaseCount { get; set; }
    }