// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

namespace AF.ECT.Data.ResultTypes;
    public partial class utility_workflow_sp_InsertWorkStatusByWorkflowIdResult
    {
        public int ws_id { get; set; }
        public byte workflowId { get; set; }
        public int statusId { get; set; }
        public byte sortOrder { get; set; }
        public bool isBoardStatus { get; set; }
        [StringLength(50)]
        public string? displayText { get; set; }
        public bool isHolding { get; set; }
        [StringLength(1)]
        public string? compo { get; set; }
        public bool? isConsult { get; set; }
        [StringLength(50)]
        public string Workflow { get; set; } = default!;
        [StringLength(50)]
        public string WorkStatus { get; set; } = default!;
    }