-- Exec core_lod_sp_GetPALDataByMemberSSN '4-3355', 'Hat'

CREATE PROCEDURE [dbo].[core_lod_sp_GetPALDataByMemberSSN]
	@member_ssn varchar(12),
	@member_lastname varchar(50)
 

AS

If LEN(@member_ssn) > 4  -- full SSN passed in
	BEGIN
--	Select 'Full'
	
		SELECT
			  '***-**-' + RIGHT(SSAN_, 4) As SSAN_
--			  ,[LAST_NAME]
--			  ,[FIRST_NAME]
--			  ,[RANK]
--			  ,[BIRTH_DATE]
			  ,[TYPE]
			  ,[RATING]
			  ,[ASC_CODE]
			  ,[BASEASSIGN]
			  ,[COMPLETEBY]
			  ,[DISPOSITION]
			  ,[SENT_TO]
			  ,[DATE__OUT]
			  ,[DATE_REC]
			  ,[FICHE]
			  ,[EXPIREDATE]
			  ,[Indefinite Waiver]
			  ,[WNLR] As Waiver_No_Longer_Required
			  ,[DIAGNOSIS]
			  ,[REMARKS]
			  --,[RWOA]
			  ,[RWOA REASON]
			  --,[TRWOA]
			  --,[RECEIVED FROM]
			  --,[He/She]
			  --,[his/her]
			  --,[him/her]
			  --,[Ret to Duty by]
			  --,[ALC-C]
			  --,[AF FORM 422 (FEB 93 FORMAT)]
			  --,[NARRATIVE SUMMARY]
			  --,[Questionnaire]
			  --,[UNIT COMMANDER'S Memo]
			  --,[IPEB ELECTION INCLUDED]
			  --,[IPEBElectedYes]
			  --,[IPEBElectedNo]
			  --,[NoHome]
			  --,[Asthma/Gen (12)]
			  --,[CAD (12-1)]
			  --,[DM (12-2)]
			  --,[HIV (12-3)]
			  --,[Psych (12-4)]
			  --,[Home Station - No mandays]
			  --,[CONUS]
			  --,[CONUS if checked first]
			  --,[1]
			  --,[3]
			  --,[3-1]
			  --,[4]
			  --,[4-1]
			  --,[4-1-1]
			  --,[4-2]
			  --,[4-3]
			  --,[4-4]
			  --,[4-5]
			  --,[5]
			  --,[6]
			  --,[6-1]
			  --,[7]
			  --,[8]
			  --,[9]
			  --,[9-1]
			  --,[10]
			  --,[10-1]
			  --,[10-2]
			  --,[10-3]
			  --,[11]
			  --,[13]
			  --,[15]
			  --,[16]
			  --,[16-1]
			  --,[16-2]
			  --,[16-2-1]
			  --,[16-3]
			  --,[16-4]
			  --,[16-5]
			  --,[16-5A]
			  --,[16-6]
			  --,[16-7]
			  --,[16-7A]
			  --,[16-7B]
			  --,[18]
			  --,[20]
			  --,[21]
			  --,[21-1]
			  --,[22]
			  --,[DQ Para Number]
			  --,[DQ Diagnosis]
			  --,[Additional Comments]
			  --,[Signature]
			  --,[Medical Evaluation Fact Sheet]
			  --,[ART and DSN]
			  ,[Discharged?]
			  ,[Retired?]
			  --,[Cancer]
			  --,[Coronary]
			  --,[DM]
			  --,[HIV]
			  --,[Musculoskeletal]
			  --,[Psych]
			  --,[Pulmonary]
			  --,[RK]
			  --,[Neuro]
			  --,[Other]
			  --,[Dental]
			  --,[GI]
			  --,[EENT]
			  --,[He/She(NotCapped)]
			  --,[DateSentToFiche]
			  --,[Renewal]
			  --,[ARCHIVE]
			  --,[RE-ACTIVATE]
			  --,[Input By]
			  --,[RcdId]
			  --,[RetiredDesc]
			  --,[DischargedDesc]
		  FROM [dbo].[PAL_Data]
		 Where SSAN_ like '%' + @member_ssn + '%'
  	END
	ELSE  -- partial SSN passed in
	BEGIN
	IF Len(LTRIM(RTrim(@member_lastname))) > 0
		BEGIN
--		Select 'Partial'
		
		SELECT
			  '***-**-' + RIGHT(SSAN_, 4) As SSAN_
--			  ,[LAST_NAME]
--			  ,[FIRST_NAME]
--			  ,[RANK]
--			  ,[BIRTH_DATE]
			  ,[TYPE]
			  ,[RATING]
			  ,[ASC_CODE]
			  ,[BASEASSIGN]
			  ,[COMPLETEBY]
			  ,[DISPOSITION]
			  ,[SENT_TO]
			  ,[DATE__OUT]
			  ,[DATE_REC]
			  ,[FICHE]
			  ,[EXPIREDATE]
			  ,[Indefinite Waiver]
			  ,[WNLR] As Waiver_No_Longer_Required
			  ,[DIAGNOSIS]
			  ,[REMARKS]
			  --,[RWOA]
			  ,[RWOA REASON]
			  --,[TRWOA]
			  --,[RECEIVED FROM]
			  --,[He/She]
			  --,[his/her]
			  --,[him/her]
			  --,[Ret to Duty by]
			  --,[ALC-C]
			  --,[AF FORM 422 (FEB 93 FORMAT)]
			  --,[NARRATIVE SUMMARY]
			  --,[Questionnaire]
			  --,[UNIT COMMANDER'S Memo]
			  --,[IPEB ELECTION INCLUDED]
			  --,[IPEBElectedYes]
			  --,[IPEBElectedNo]
			  --,[NoHome]
			  --,[Asthma/Gen (12)]
			  --,[CAD (12-1)]
			  --,[DM (12-2)]
			  --,[HIV (12-3)]
			  --,[Psych (12-4)]
			  --,[Home Station - No mandays]
			  --,[CONUS]
			  --,[CONUS if checked first]
			  --,[1]
			  --,[3]
			  --,[3-1]
			  --,[4]
			  --,[4-1]
			  --,[4-1-1]
			  --,[4-2]
			  --,[4-3]
			  --,[4-4]
			  --,[4-5]
			  --,[5]
			  --,[6]
			  --,[6-1]
			  --,[7]
			  --,[8]
			  --,[9]
			  --,[9-1]
			  --,[10]
			  --,[10-1]
			  --,[10-2]
			  --,[10-3]
			  --,[11]
			  --,[13]
			  --,[15]
			  --,[16]
			  --,[16-1]
			  --,[16-2]
			  --,[16-2-1]
			  --,[16-3]
			  --,[16-4]
			  --,[16-5]
			  --,[16-5A]
			  --,[16-6]
			  --,[16-7]
			  --,[16-7A]
			  --,[16-7B]
			  --,[18]
			  --,[20]
			  --,[21]
			  --,[21-1]
			  --,[22]
			  --,[DQ Para Number]
			  --,[DQ Diagnosis]
			  --,[Additional Comments]
			  --,[Signature]
			  --,[Medical Evaluation Fact Sheet]
			  --,[ART and DSN]
			  ,[Discharged?]
			  ,[Retired?]
			  --,[Cancer]
			  --,[Coronary]
			  --,[DM]
			  --,[HIV]
			  --,[Musculoskeletal]
			  --,[Psych]
			  --,[Pulmonary]
			  --,[RK]
			  --,[Neuro]
			  --,[Other]
			  --,[Dental]
			  --,[GI]
			  --,[EENT]
			  --,[He/She(NotCapped)]
			  --,[DateSentToFiche]
			  --,[Renewal]
			  --,[ARCHIVE]
			  --,[RE-ACTIVATE]
			  --,[Input By]
			  --,[RcdId]
			  --,[RetiredDesc]
			  --,[DischargedDesc]
		  FROM [dbo].[PAL_Data]
		 Where CHARINDEX(@member_ssn, SSAN_) > 0
			And CharIndex(Upper(@member_lastname), Upper(LAST_NAME)) > 0
		END
	END
GO

