
CREATE PROCEDURE [dbo].[member_sp_findBySSN]
	@SSN char(9)

AS

SELECT TOP 1
	SSN, FIRST_NAME, LAST_NAME, MIDDLE_NAMES
	,PAS_NUMBER UNIT_CODE, M.COMPO, GRCODE, RANK, GRADE, DOB
	,S.LONG_NAME UNIT_NAME, S.CS_ID UNIT_ID, C.Compo_Descr, RANK_TITLE
FROM 
	VW_MEMBERDATA M
JOIN 
	COMMAND_STRUCT S ON S.PAS_CODE = M.PAS_NUMBER
JOIN core_lkupCompo C ON C.compo = M.COMPO
WHERE 
	SSN = @SSN


--[member_sp_findBySSN] '22222222A'
GO

