// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents Nonunit Personnel data imported from AFRC Oracle.
/// </summary>
public partial class AfrcOracleNonunitPersonnelDatum
{
    public string? PersId { get; set; }

    public string? Username { get; set; }

    public string? Name { get; set; }

    public string? FirstName { get; set; }

    public string? Mi { get; set; }

    public string? LastName { get; set; }

    public string? NameSuffix { get; set; }

    public string? CreatedBy { get; set; }

    public string? CreatedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public string? ModifiedDate { get; set; }

    public string? CsId { get; set; }

    public string? DutySection { get; set; }

    public string? Sex { get; set; }

    public string? EMailHome { get; set; }

    public string? EMailWork { get; set; }

    public string? EMailUnit { get; set; }

    public string? ContactInfo { get; set; }

    public string? ResAddress1 { get; set; }

    public string? ResAddress2 { get; set; }

    public string? ResCity { get; set; }

    public string? ResPostalCode { get; set; }

    public string? ResCountry { get; set; }

    public string? ResState { get; set; }
}
