// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents Manpower All data imported from AFRC Oracle.
/// </summary>
public partial class AfrcOracleManpowerAllDatum
{
    public string? MpId { get; set; }

    public string? MpFilePart { get; set; }

    public string? PasCode { get; set; }

    public string? AuthRecYn { get; set; }

    public string? WarRecYn { get; set; }

    public string? PeaceRecYn { get; set; }

    public string? AuthAfscPfx { get; set; }

    public string? AuthAfsc { get; set; }

    public string? AuthAfscSfx { get; set; }

    public string? AuthGrade { get; set; }

    public string? WarAfscPfx { get; set; }

    public string? WarAfsc { get; set; }

    public string? WarAfscSfx { get; set; }

    public string? WarGrade { get; set; }

    public string? PeaceAfscPfx { get; set; }

    public string? PeaceAfsc { get; set; }

    public string? PeaceAfscSfx { get; set; }

    public string? PeaceGrade { get; set; }

    public string? ArtYn { get; set; }

    public string? PosNbr { get; set; }

    public string? GainingCommandCode { get; set; }

    public string? ReqType { get; set; }

    public string? FundYn { get; set; }

    public string? InstLoc { get; set; }

    public string? AuthUnitNbr { get; set; }

    public string? AuthUnitKind { get; set; }

    public string? AuthUnitType { get; set; }

    public string? WarUnitNbr { get; set; }

    public string? WarUnitKind { get; set; }

    public string? WarUnitType { get; set; }

    public string? PeaceUnitNbr { get; set; }

    public string? PeaceUnitKind { get; set; }

    public string? PeaceUnitType { get; set; }

    public string? OperLoc { get; set; }

    public string? Det { get; set; }

    public string? Pec { get; set; }

    public string? Utc { get; set; }

    public string? GradeType { get; set; }

    public string? CommandCode { get; set; }

    public string? PosNbrXref { get; set; }

    public string? Rpi { get; set; }

    public string? Osc { get; set; }

    public string? Fac { get; set; }

    public string? Occ { get; set; }

    public string? DutyCode { get; set; }

    public string? AuthAmt { get; set; }

    public string? OscDesc { get; set; }

    public string? FacTitle { get; set; }

    public string? Ilk { get; set; }

    public string? CmdRmk { get; set; }

    public string? DutyTitle { get; set; }

    public string? PosNbrActual { get; set; }
}
