// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents ALOD Pas Raw data.
/// </summary>
public partial class AlodPasRaw
{
    public string? Aav3 { get; set; }

    public string? Aku121 { get; set; }

    public string? Anu45 { get; set; }

    public string? Anw { get; set; }

    public string? Afp5 { get; set; }

    public string? Ans { get; set; }

    public string? Ant20 { get; set; }

    public string? Beb6 { get; set; }

    public string? Crx { get; set; }

    public string? OrganizationId { get; set; }

    public string? Afp1 { get; set; }

    public string? Amx5 { get; set; }

    public string? Ana { get; set; }

    public string? Amy { get; set; }

    public string? Anc { get; set; }

    public string? Arb { get; set; }

    public string? Ant { get; set; }

    public string? Ant2 { get; set; }

    public string? Anu30 { get; set; }

    public string? Cap { get; set; }

    public string? Acr1 { get; set; }

    public string? Cap2 { get; set; }

    public string? Alb { get; set; }

    public string? Anu { get; set; }

    public string? Atj { get; set; }

    public string? Aep { get; set; }

    public string? Xwx115 { get; set; }

    public string? Anf { get; set; }

    public string? Uic { get; set; }

    public string? Crz { get; set; }

    public string? ProjectedChangeEffectiveDate { get; set; }

    public string? Aen53 { get; set; }

    public string? Aen62 { get; set; }

    public string? Aen43 { get; set; }

    public string? Aen29 { get; set; }

    public string? Aen15 { get; set; }

    public string? Aku60 { get; set; }

    public string? Aku19 { get; set; }

    public string? Aku51 { get; set; }

    public string? MedFacNr { get; set; }

    public string? Aaa195 { get; set; }

    public string? Aaa222 { get; set; }

    public string? Aaa199 { get; set; }

    public string? Ofprml { get; set; }

    public string? LocationId { get; set; }

    public string? DateFrom { get; set; }

    public string? DateTo { get; set; }

    public string? Efa { get; set; }

    public string? Ady7 { get; set; }

    public string? EndDateActive { get; set; }

    public string? LookupCode { get; set; }

    public string? RiTimestamp { get; set; }

    public string? Asq7 { get; set; }

    public string? Aba71 { get; set; }

    public string? Aba72 { get; set; }

    public string? Unit { get; set; }

    public string? Amf504 { get; set; }

    public string? MpfPasAdminMeaning { get; set; }

    public string? Aev24 { get; set; }

    public string? Aew { get; set; }

    public string? Ajg { get; set; }

    public string? Ajh8 { get; set; }

    public string? Ajj { get; set; }

    public string? Amf503 { get; set; }

    public string? Aeq1 { get; set; }

    public string? Ael { get; set; }

    public string? Aen1 { get; set; }

    public string? Amf303 { get; set; }

    public string? Abc2 { get; set; }

    public string? Afc175 { get; set; }

    public int? ParentCsId { get; set; }

    public string? UnitDerived { get; set; }
}
