// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a mapping between workflows and permissions.
/// </summary>
public partial class CoreWorkflowPermission
{
    /// <summary>
    /// Gets or sets the workflow identifier.
    /// </summary>
    public byte? WorkflowId { get; set; }

    /// <summary>
    /// Gets or sets the permission identifier.
    /// </summary>
    public short? PermId { get; set; }

    /// <summary>
    /// Gets or sets the navigation property to the associated permission.
    /// </summary>
    public virtual CorePermission? Perm { get; set; }

    /// <summary>
    /// Gets or sets the navigation property to the associated workflow.
    /// </summary>
    public virtual CoreWorkflow? Workflow { get; set; }
}
