// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a type classification for PEPP (Physical Evaluation for Performance and Promotion) cases.
/// </summary>
public partial class CoreLkupPepptype
{
    /// <summary>
    /// Gets or sets the unique identifier for the PEPP type.
    /// </summary>
    public int TypeId { get; set; }

    /// <summary>
    /// Gets or sets the name of the PEPP type.
    /// </summary>
    public string TypeName { get; set; } = null!;

    /// <summary>
    /// Gets or sets a value indicating whether this PEPP type is currently active.
    /// </summary>
    public bool Active { get; set; }
}
