// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a country in the Electronic Case Tracking system.
/// </summary>
/// <remarks>
/// This lookup table defines countries for address information, geographic filtering,
/// and international case handling. Includes all countries where U.S. military personnel
/// may be stationed or where incidents may occur.
/// 
/// The Country field contains the full country name (e.g., "United States", "Germany",
/// "Japan"), while the Abbr field contains standard abbreviations or country codes
/// (e.g., "USA", "DEU", "JPN").
/// 
/// This table is used for:
/// - Member and facility address information
/// - International incident location tracking
/// - Geographic reporting and filtering
/// - Command structure organization for overseas units
/// 
/// The system tracks creation and modification metadata for audit purposes and to
/// support data governance requirements.
/// </remarks>
public partial class CoreLkupCountry
{
    /// <summary>
    /// Gets or sets the Country Id identifier.
    /// </summary>
    public int CountryId { get; set; }

    /// <summary>
    /// Gets or sets the  country.
    /// </summary>
    public string Country { get; set; } = null!;

    /// <summary>
    /// Gets or sets the Abbr.
    /// </summary>
    public string? Abbr { get; set; }

    /// <summary>
    /// Gets or sets the Created Date date.
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// Gets or sets the  user identifier who created this record.
    /// </summary>
    public string CreatedBy { get; set; } = null!;

    /// <summary>
    /// Gets or sets the Modified Date date.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    /// <summary>
    /// Gets or sets the  user identifier who last modified this record.
    /// </summary>
    public string ModifiedBy { get; set; } = null!;
}
