// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents individual permissions granted directly to a specific user.
/// </summary>
/// <remarks>
/// CoreUserPermission provides user-level permission overrides that grant or deny specific
/// permissions to individual users, bypassing the group-based permission model. This is
/// useful for exceptions, temporary access grants, or special user requirements.
/// 
/// The Status field ("Active", "Inactive", "Suspended") controls whether the permission
/// is currently effective. This composite key relationship (UserId + PermId) ensures each
/// user-permission combination is unique.
/// 
/// User permissions are evaluated alongside group permissions during authorization checks,
/// with user-level permissions typically taking precedence over group-level permissions.
/// </remarks>
public partial class CoreUserPermission
{
    /// <summary>
    /// Gets or sets the User Id identifier.
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// Gets or sets the Perm Id identifier.
    /// </summary>
    public short PermId { get; set; }

    /// <summary>
    /// Gets or sets the Status.
    /// </summary>
    public string Status { get; set; } = null!;

    /// <summary>
    /// Gets or sets the Perm.
    /// </summary>
    public virtual CorePermission Perm { get; set; } = null!;

    /// <summary>
    /// Gets or sets the User.
    /// </summary>
    public virtual CoreUser User { get; set; } = null!;
}
