// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a group or role authorized to complete specific workflow stages in the Electronic Case Tracking system.
/// </summary>
/// <remarks>
/// Completed-by groups define which organizational roles or functional groups are authorized to complete
/// specific case types or workflow stages. Examples might include "Medical Board", "Legal Review Board",
/// "Command Approval Authority", "Personnel Office", etc.
/// 
/// These groups are linked to workflows via CoreWorkflowCompletedByGroupMap, establishing which groups
/// have authority to process and approve cases in specific workflows. This enables role-based access control
/// and ensures cases are reviewed by the appropriate authorities.
/// </remarks>
public partial class CoreCompletedByGroup
{
    /// <summary>
    /// Gets or sets the Id identifier.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    public string Name { get; set; } = null!;
}
