// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a Dev Login entity.
/// </summary>
public partial class DevLogin
{
    /// <summary>
    /// Gets or sets the User Id identifier.
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// Gets or sets the Compo.
    /// </summary>
    public string Compo { get; set; } = null!;

    /// <summary>
    /// Gets or sets the Role Id identifier.
    /// </summary>
    public int? RoleId { get; set; }
}
