// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents Form 348 Sarc Finding data.
/// </summary>
public partial class Form348SarcFinding
{
    /// <summary>
    /// Gets or sets the Id identifier.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the Sarc Id identifier.
    /// </summary>
    public int SarcId { get; set; }

    /// <summary>
    /// Gets or sets the Ptype.
    /// </summary>
    public short? Ptype { get; set; }

    /// <summary>
    /// Gets or sets the  Social Security Number.
    /// </summary>
    public string? Ssn { get; set; }

    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Gets or sets the  military grade/rank.
    /// </summary>
    public string? Grade { get; set; }

    /// <summary>
    /// Gets or sets the Compo.
    /// </summary>
    public string? Compo { get; set; }

    /// <summary>
    /// Gets or sets the  findings.
    /// </summary>
    public int? Finding { get; set; }

    /// <summary>
    /// Gets or sets the  comments/remarks.
    /// </summary>
    public string? Remarks { get; set; }

    /// <summary>
    /// Gets or sets the  user identifier who created this record.
    /// </summary>
    public int? CreatedBy { get; set; }

    /// <summary>
    /// Gets or sets the Created Date date.
    /// </summary>
    public DateTime? CreatedDate { get; set; }

    /// <summary>
    /// Gets or sets the  user identifier who last modified this record.
    /// </summary>
    public int? ModifiedBy { get; set; }

    /// <summary>
    /// Gets or sets the Modified Date date.
    /// </summary>
    public DateTime? ModifiedDate { get; set; }

    /// <summary>
    /// Gets or sets the Pascode.
    /// </summary>
    public string? Pascode { get; set; }

    /// <summary>
    /// Gets or sets the  military grade/rank.
    /// </summary>
    public string? Rank { get; set; }

    /// <summary>
    /// Gets or sets the Findings Text.
    /// </summary>
    public string? FindingsText { get; set; }

    /// <summary>
    /// Gets or sets the Concur.
    /// </summary>
    public string? Concur { get; set; }

    /// <summary>
    /// Gets or sets the Created By Navigation.
    /// </summary>
    public virtual CoreUser? CreatedByNavigation { get; set; }

    /// <summary>
    /// Gets or sets the Modified By Navigation.
    /// </summary>
    public virtual CoreUser? ModifiedByNavigation { get; set; }

    /// <summary>
    /// Gets or sets the Ptype Navigation.
    /// </summary>
    public virtual CoreLkupPersonnelType? PtypeNavigation { get; set; }

    /// <summary>
    /// Gets or sets the Sarc.
    /// </summary>
    public virtual Form348Sarc Sarc { get; set; } = null!;
}
