// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents imported Lod Investigation Rpt data for system migration/integration.
/// </summary>
public partial class ImpLodInvestigationRpt
{
    public string? LirId { get; set; }

    public string? LodId { get; set; }

    public string? ReportDate { get; set; }

    public string? InvestigationOf { get; set; }

    public string? Status { get; set; }

    public string? StatusInactiveType { get; set; }

    public string? StatusDurationStart { get; set; }

    public string? StatusDurationFinish { get; set; }

    public string? AddressedTo { get; set; }

    public string? CircumstancesTime { get; set; }

    public string? CircumstancesPlace { get; set; }

    public string? SustainedDesc { get; set; }

    public string? Diagnosis { get; set; }

    public string? PresentForDutyYn { get; set; }

    public string? AbsentWithAuthYn { get; set; }

    public string? IntentionalMisconductYn { get; set; }

    public string? MentallySoundYn { get; set; }

    public string? Remarks { get; set; }

    public string? Findings { get; set; }

    public string? InvOfficerPersId { get; set; }

    public string? AaDate { get; set; }

    public string? RaPersId { get; set; }

    public string? RaDate { get; set; }

    public string? CreatedBy { get; set; }

    public string? CreatedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public string? ModifiedDate { get; set; }

    public string? WingJaPersId { get; set; }

    public string? WingJaApprovedYn { get; set; }

    public string? WingJaReasons { get; set; }

    public string? WingAaPersId { get; set; }

    public string? WingAaApprovedYn { get; set; }

    public string? WingAaFindings { get; set; }

    public string? WingAaReasons { get; set; }

    public string? HqsgPersId { get; set; }

    public string? HqsgFindings { get; set; }

    public string? HqsgReasons { get; set; }

    public string? HqjaPersId { get; set; }

    public string? HqjaFindings { get; set; }

    public string? HqjaReasons { get; set; }

    public string? RaReasons { get; set; }

    public string? HqaaPersId { get; set; }

    public string? FinalApprovalFindings { get; set; }

    public string? HqaaReasons { get; set; }

    public string? WingJaName { get; set; }

    public string? WingJaUnit { get; set; }

    public string? WingJaGrade { get; set; }

    public string? WingAaName { get; set; }

    public string? WingAaUnit { get; set; }

    public string? WingAaGrade { get; set; }

    public string? RaName { get; set; }

    public string? RaUnit { get; set; }

    public string? RaGrade { get; set; }

    public string? HqsgName { get; set; }

    public string? HqsgUnit { get; set; }

    public string? HqsgGrade { get; set; }

    public string? HqjaName { get; set; }

    public string? HqjaUnit { get; set; }

    public string? HqjaGrade { get; set; }

    public string? HqaaName { get; set; }

    public string? HqaaUnit { get; set; }

    public string? HqaaGrade { get; set; }

    public string? HqsrPersId { get; set; }

    public string? HqsrName { get; set; }

    public string? HqsrGrade { get; set; }

    public string? HqsrUnit { get; set; }

    public string? HqsrFindings { get; set; }

    public string? HqsrReasons { get; set; }
}
