// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents imported Member data for system migration/integration.
/// </summary>
public partial class ImpMember
{
    public string? Ssan { get; set; }

    public string? FirstName { get; set; }

    public string? MiddleNames { get; set; }

    public string? LastName { get; set; }

    public string? Suffix { get; set; }

    public string? SexSvcMbr { get; set; }

    public string? PasGaining { get; set; }

    public string? AsgReptNltDate { get; set; }

    public string? RcdId { get; set; }

    public string? RecStatCurr { get; set; }

    public string? Pas { get; set; }

    public string? CommDutyPhone { get; set; }

    public string? OfficeSymbol { get; set; }

    public string? LocalAddrStreet1st { get; set; }

    public string? LocalAddrStreet2nd { get; set; }

    public string? LocalAddrCity { get; set; }

    public string? LocalAddrState { get; set; }

    public string? LocalAddrZip { get; set; }

    public string? HomePhone { get; set; }

    public string? CurrStreetAddr1st { get; set; }

    public string? CurrStreetAddr2nd { get; set; }

    public string? AdrsMailDomCity { get; set; }

    public string? AdrsMailDomState { get; set; }

    public string? AdrsMailZip { get; set; }

    public string? GrCurr { get; set; }

    public string? Dor { get; set; }

    public string? DyPosnNr { get; set; }

    public string? Dafsc { get; set; }

    public string? DyEffDate { get; set; }

    public string? DutyStatus { get; set; }

    public string? DutyStatusEffDate { get; set; }

    public string? DutyStatusExpDate { get; set; }

    public string? DeplAvailStatusAdmin { get; set; }

    public string? DeplAvailStatusAExD { get; set; }

    public string? DeplAvailStatusPhys { get; set; }

    public string? DeplAvailStatusPExD { get; set; }

    public string? DeplAvailStatusLegal { get; set; }

    public string? DeplAvailStatusLExD { get; set; }

    public string? DeplAvailStatusTime { get; set; }

    public string? DeplAvailStatusTExD { get; set; }

    public string? Pafsc { get; set; }

    public string? Afsc2 { get; set; }

    public string? Afsc3 { get; set; }

    public string? Dob { get; set; }

    public string? RetSepEffDateProj { get; set; }

    public string? Dos { get; set; }

    public string? Eto { get; set; }

    public string? SvcComp { get; set; }

    public string? Tafcsd { get; set; }

    public string? Tafmsd { get; set; }

    public string? Ets { get; set; }

    public string? CurrAeroRating { get; set; }

    public string? AvnSvcCode { get; set; }

    public string? AvnSvcCodeDate { get; set; }
}
