// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents imported ort Error Log data for system migration/integration.
/// </summary>
public partial class ImportErrorLog
{
    public string? UpdatingData { get; set; }

    public string? StoredProc { get; set; }

    public string? Message { get; set; }

    public int? Rcphalodid { get; set; }

    public DateTime? Time { get; set; }

    public string? ErrorMessage { get; set; }
}
