// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents imported Person Process data for system migration/integration.
/// </summary>
public partial class ImpPersonProcess
{
    public string? PpId { get; set; }

    public string? PiId { get; set; }

    public string? ProcessName { get; set; }

    public string? PvsId { get; set; }

    public string? StatusMeaning { get; set; }

    public string? LodId { get; set; }

    public string? ProcessedBy { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string? CompletedYn { get; set; }

    public string? FinalResult { get; set; }

    public string? Remark { get; set; }

    public string? CreatedBy { get; set; }

    public string? CreatedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public string? ModifiedDate { get; set; }

    public string? CallingPpId { get; set; }
}
