// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents imported Personnel Feed data for system migration/integration.
/// </summary>
public partial class ImpPersonnelFeed
{
    public string? PersId { get; set; }

    public string? PosNbr { get; set; }

    public string? Name { get; set; }

    public string? FirstName { get; set; }

    public string? Mi { get; set; }

    public string? LastName { get; set; }

    public string? NameSuffix { get; set; }

    public string? Rank { get; set; }

    public string? ClearanceId { get; set; }

    public string? DutyLoc { get; set; }

    public string? DavCode { get; set; }

    public string? FlyerId { get; set; }

    public string? Dob { get; set; }

    public string? Doa { get; set; }

    public string? Doe { get; set; }

    public string? Dor { get; set; }

    public string? Ets { get; set; }

    public string? PafscPfx { get; set; }

    public string? Pafsc { get; set; }

    public string? PafscSfx { get; set; }

    public string? Sei { get; set; }

    public string? SafscPfx { get; set; }

    public string? Safsc { get; set; }

    public string? SafscSfx { get; set; }

    public string? TafscPfx { get; set; }

    public string? Tafsc { get; set; }

    public string? TafscSfx { get; set; }

    public string? DafscPfx { get; set; }

    public string? Dafsc { get; set; }

    public string? DafscSfx { get; set; }

    public string? CafscPfx { get; set; }

    public string? Cafsc { get; set; }

    public string? CafscSfx { get; set; }

    public string? HomePhone { get; set; }

    public string? MailAddress1 { get; set; }

    public string? MailAddress2 { get; set; }

    public string? MailCity { get; set; }

    public string? MailState { get; set; }

    public string? MailPostalCode { get; set; }

    public string? PasAtchTrng { get; set; }

    public string? TrngAfsc { get; set; }

    public string? CivArtId { get; set; }

    public string? CreatedBy { get; set; }

    public string? CreatedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public string? ModifiedDate { get; set; }
}
