// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents imported Process data for system migration/integration.
/// </summary>
public partial class ImpProcess
{
    public string? ProcId { get; set; }

    public string? CsId { get; set; }

    public string? ProcessName { get; set; }

    public string? ProcType { get; set; }

    public string? ProcClassification { get; set; }

    public string? ParentProcId { get; set; }

    public string? Version { get; set; }

    public string? VersionDate { get; set; }

    public string? ActiveYn { get; set; }

    public string? MultRespAllowedYn { get; set; }

    public string? RespRequiredYn { get; set; }

    public string? PaperForm { get; set; }

    public string? MonthsValid { get; set; }

    public string? ProcessHelpYn { get; set; }

    public string? RoutineType { get; set; }

    public string? RoutineName { get; set; }

    public string? Description { get; set; }

    public string? ProgramCode { get; set; }

    public string? WorkflowMultipleYn { get; set; }

    public string? CreatedBy { get; set; }

    public string? CreatedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public string? ModifiedDate { get; set; }

    public string? NewWindowYn { get; set; }

    public string? DefaultResult { get; set; }

    public string? InboxParam { get; set; }

    public string? InboxValue { get; set; }
}
