// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents imported Personnel data for system migration/integration.
/// </summary>
public partial class ImpPersonnel
{
    public string? PersId { get; set; }

    public string? Ssn { get; set; }

    public string? Username { get; set; }

    public string? DutySection { get; set; }

    public string? Sex { get; set; }

    public string? EMailHome { get; set; }

    public string? EMailWork { get; set; }

    public string? EMailUnit { get; set; }

    public string? ContactInfo { get; set; }

    public string? ResAddress1 { get; set; }

    public string? ResAddress2 { get; set; }

    public string? ResCity { get; set; }

    public string? ResPostalCode { get; set; }

    public string? ResCountry { get; set; }

    public string? ResState { get; set; }

    public string? CreatedBy { get; set; }

    public string? CreatedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public string? ModifiedDate { get; set; }

    public string? AltDavCode { get; set; }

    public string? AltDavCodeExpire { get; set; }

    public string? AltFlyerId { get; set; }

    public string? AltFlyerIdExpire { get; set; }

    public string? AltPasAtchTrng { get; set; }

    public string? AltPasAtchTrngExpire { get; set; }

    public string? SpclOpsYn { get; set; }
}
