// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents imported Process Instance data for system migration/integration.
/// </summary>
public partial class ImpProcessInstance
{
    public string? PiId { get; set; }

    public string? ProcId { get; set; }

    public string? ProcessName { get; set; }

    public string? LodId { get; set; }

    public string? PersId { get; set; }

    public string? StartDate { get; set; }

    public string? EndDate { get; set; }

    public string? CompletedYn { get; set; }

    public string? CreatedBy { get; set; }

    public string? CreatedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public string? ModifiedDate { get; set; }

    public string? ScriptClosed { get; set; }

    public string? DueDate { get; set; }

    public string? InstType { get; set; }

    public string? ExpirationDate { get; set; }

    public string? ReqCompleteDate { get; set; }

    public string? DeploymentId { get; set; }
}
