// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents imported Tmp Username data for system migration/integration.
/// </summary>
public partial class ImpTmpUsername
{
    public string? Username { get; set; }
}
