// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a Member Datum entity.
/// </summary>
public partial class MemberDatum
{
    public string Ssan { get; set; } = null!;

    public string? FirstName { get; set; }

    public string? MiddleNames { get; set; }

    public string? LastName { get; set; }

    public string? Suffix { get; set; }

    /// <summary>
    /// The gaining PAS code for a member&apos;s pending reassignment.
    /// </summary>
    public string? PasGaining { get; set; }

    /// <summary>
    /// The report not later than date (RNLTD) for Regular component assignments or effective date of change in strength accountability (EDCSA) for a member of the Air National Guard or AF Reserve upon reassignment.  This effectively starts strength accountability for new unit and stops accountability for losing unit.
    /// </summary>
    public DateTime? AsgReptNltDate { get; set; }

    /// <summary>
    /// Member&apos;s&apos; FILE_TYPE (AA=AF Enlisted Regular Mbr, AG=AF Enlisted ANG Mbr,AR=AF Enlisted Reserve Mbr,BA=AF Officer Regular Mbr, BG=AF Officer ANG  Mbr, BR=AF Officer Reserve Mbr, EX=Ex-employee, etc)
    /// </summary>
    public string? RcdId { get; set; }

    /// <summary>
    /// Member&apos;s Record Stats (i.e. 10=Active No Projected Action, 20=Active Projected Separation No Projected Assignment,etc.).
    /// </summary>
    public string? RecStatCurr { get; set; }

    /// <summary>
    /// Member&apos;s organization of assignment
    /// </summary>
    public string? Pas { get; set; }

    /// <summary>
    /// PHONE_NUMBER as it pertains to the member based on PHONE_TYPE.
    /// </summary>
    public string? CommDutyPhone { get; set; }

    public string? OfficeSymbol { get; set; }

    /// <summary>
    /// A 50-character string containing the first line of the delivery address for a person.  This typically contains aspects of the street address.
    /// </summary>
    public string? LocalAddrStreet { get; set; }

    /// <summary>
    /// A 30-character string containing the city designation in an address.
    /// </summary>
    public string? LocalAddrCity { get; set; }

    /// <summary>
    /// The code that identifies the state in the United States used as a component of an address.
    /// </summary>
    public string? LocalAddrState { get; set; }

    /// <summary>
    /// PHONE_NUMBER as it pertains to the member based on PHONE_TYPE.
    /// </summary>
    public string? HomePhone { get; set; }

    /// <summary>
    /// A 30-character string containing the city designation in an address.
    /// </summary>
    public string? AdrsMailDomCity { get; set; }

    /// <summary>
    /// The code that identifies the state in the United States used as a component of an address.
    /// </summary>
    public string? AdrsMailDomState { get; set; }

    /// <summary>
    /// The postal code used in a person&apos;s delivery address.
    /// </summary>
    public string? AdrsMailZip { get; set; }

    /// <summary>
    /// The two-digit code used to uniquely identify a particular military pay grade/rank.  The textual equivalent is contained in the Cleartext column of grade (i.e. code &apos;34&apos; corresponds to SGT.
    /// </summary>
    public int GrCurr { get; set; }

    /// <summary>
    /// Position number is a nine character field in MDS.  It is used as part of the database key for all manpower requirement records.  The attribute consists of a seven character number and a two character Major Command (MAJCOM) Identifier.   
    /// </summary>
    public string? DyPosnNr { get; set; }

    /// <summary>
    /// Duty Air Force Specialty Code (DAFSC).  The type of Air Force Specialty that applies to a member while assigned to a specific position.  7 positions include Prefix and Suffix
    /// </summary>
    public string? Dafsc { get; set; }

    /// <summary>
    /// DUTY_STATUS
    /// </summary>
    public string? DutyStatus { get; set; }

    public DateTime? DutyStatusEffDate { get; set; }

    public DateTime? DutyStatusExpDate { get; set; }

    /// <summary>
    /// Identifies the deployment availability status of an individual by category of limitation as determined by related administrative actions.
    /// </summary>
    public string? DeplAvailStatusAdmin { get; set; }

    /// <summary>
    /// Date administrative code expires.
    /// </summary>
    public DateTime? DeplAvailStatusAExD { get; set; }

    /// <summary>
    /// Identifies the deployment availability status of an individual by category of limitation as determined by related physical actions.
    /// </summary>
    public string? DeplAvailStatusPhys { get; set; }

    /// <summary>
    /// Date physical code expires.
    /// </summary>
    public DateTime? DeplAvailStatusPExD { get; set; }

    /// <summary>
    /// Identifies the deployment availability status of an individual by category of limitation as determined by related legal actions.
    /// </summary>
    public string? DeplAvailStatusLegal { get; set; }

    /// <summary>
    /// Date legal code expires.
    /// </summary>
    public DateTime? DeplAvailStatusLExD { get; set; }

    /// <summary>
    /// Identifies the deployment availability status of an individual by category of limitation as determined by related personnel actions.
    /// </summary>
    public string? DeplAvailStatusTime { get; set; }

    /// <summary>
    /// Date time code expires.
    /// </summary>
    public DateTime? DeplAvailStatusTExD { get; set; }

    /// <summary>
    /// Individual&apos;s Air Force Specialty Code (AFSC) require common qualifications identify by a title.  An ability, skill, special qualification or system designator not restrcited to a single AFSC (i.e. the Prefix &apos;T&apos;  affixed to an AFSC indicates the person has been qualified as a Formal Training Instructor.  The primary AFSC normally denotes the AFSC the member is most qualified to perform duty in.  The 7-digit code includes Prefix and Suffix.
    /// </summary>
    public string? Pafsc { get; set; }

    /// <summary>
    /// Individual&apos;s Air Force Specialty Code (AFSC) require common qualifications identify by a title.  An ability, skill, special qualification or system designator not restrcited to a single AFSC (i.e. the Prefix &apos;T&apos;  affixed to an AFSC indicates the person has been qualified as a Formal Training Instructor.  The secondary AFSC is the specialty the member is second highest qualified to perform duty in.  The 7-digit code includes Prefix and Suffix.
    /// </summary>
    public string? Afsc2 { get; set; }

    /// <summary>
    /// Individual&apos;s Air Force Specialty Code (AFSC) require common qualifications identify by a title.  An ability, skill, special qualification or system designator not restrcited to a single AFSC (i.e. the Prefix &apos;T&apos;  affixed to an AFSC indicates the person has been qualified as a Formal Training Instructor.  The third AFSC is the specialty the member is least likely qualified to perform duty in.  The 7-digit code includes Prefix and Suffix.
    /// </summary>
    public string? Afsc3 { get; set; }

    /// <summary>
    /// Code denoting the sex of the service member.  (Null)
    /// </summary>
    public string? SexSvcMbr { get; set; }

    /// <summary>
    /// Date of Birth of the Service member.  (NULL) 
    /// </summary>
    public DateTime? Dob { get; set; }

    /// <summary>
    /// The date a member is projected to separate from the Air Force enlisted force.  Member&apos;s Date of Separation one day prior to retirement date.
    /// </summary>
    public DateTime? RetSepEffDateProj { get; set; }

    /// <summary>
    /// Date a member is due to separate from the service.
    /// </summary>
    public DateTime? Dos { get; set; }

    /// <summary>
    /// Members Service Component (R=Regular, G=Guard, V=Reserve, C=Civilian, T=Temporary)
    /// </summary>
    public string? SvcComp { get; set; }

    /// <summary>
    /// Total Active Federal Commission Service Date.
    /// </summary>
    public DateTime? Tafcsd { get; set; }

    /// <summary>
    /// Total Active Federal Military Service Date.
    /// </summary>
    public DateTime? Tafmsd { get; set; }

    /// <summary>
    /// Expiration Term of Service.  The date a member&apos;s term of service expires.
    /// </summary>
    public DateTime? Ets { get; set; }

    /// <summary>
    /// A four character string containing the Personnel Accounting Symbol (PAS) associated with a given unit.  The PAS_MPF-NUMBER, MAJCOM_ID and PAS_NUMBER make up the PAS Code.  
    /// </summary>
    public string? PasNumber { get; set; }

    /// <summary>
    /// Military Personnel Flight Address ZIP code. ZIP code is a system established in 1963 that uses 5-digit codes to identify the individual post offices or delivery stations in metropolitan areas associated with an address.  The basic ZIP Code format consists 
    /// </summary>
    public string? Zip { get; set; }

    public bool? Deleted { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string? AttachPas { get; set; }

    public virtual CoreLkupGrade GrCurrNavigation { get; set; } = null!;
}
