// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a Special Cases Lod Case entity.
/// </summary>
public partial class SpecialCasesLodCase
{
    public string? Status { get; set; }

    public string? Position { get; set; }

    public string? Location { get; set; }
}
