

CREATE VIEW [dbo].[VW_MEMBERDATA]

AS

SELECT SSAN SSN, FIRST_NAME, LAST_NAME, MIDDLE_NAMES
	,DOB, PAS_NUMBER, SVC_COMP COMPO,GR_CURR GRCODE
	,G.RANK, G.GRADE, G.TITLE RANK_TITLE
FROM MemberData M
LEFT JOIN core_LKUPGRADE G ON G.CODE = M.GR_CURR
GO

