CREATE TABLE [DBSign].[DBS_USER_SIG_OLD] (
    [USER_ID]           INT      NOT NULL,
    [SCOPE_ID]          INT      NOT NULL,
    [DBS_CERT_ID]       INT      NOT NULL,
    [DBS_SIGN_DATE]     DATETIME NOT NULL,
    [DBS_SIGNATURE]     IMAGE    NOT NULL,
    [DBS_SIGN_DATE_GMT] CHAR (1) NULL
);
GO

