CREATE TABLE [DBSign].[DBS_DATA_TYPE_MSTR] (
    [DATA_TYPE_CODE]    INT           NOT NULL,
    [DATA_TYPE_NAME]    VARCHAR (30)  NULL,
    [COLUMN_FMT_TEXT]   VARCHAR (255) NULL,
    [VALUE_FMT_TEXT]    VARCHAR (255) NULL,
    [NATIVE_TYPE_NAME]  VARCHAR (255) NULL,
    [NATIVE_HAS_PARAMS] CHAR (1)      NULL,
    [DBS_INTERNAL_FLG]  CHAR (1)      NULL,
    [BLOB_TYPE_CODE]    CHAR (1)      NULL
);
GO

