CREATE TABLE [DBSign].[DBS_USER_SIG] (
    [USER_ID]           INT      NOT NULL,
    [DBS_CERT_ID]       INT      NOT NULL,
    [DBS_SIGN_DATE]     DATETIME NOT NULL,
    [DBS_SIGN_DATE_GMT] CHAR (1) NOT NULL,
    [DBS_SIGNATURE]     IMAGE    NOT NULL,
    PRIMARY KEY CLUSTERED ([USER_ID] ASC)
);
GO

