CREATE TABLE [DBSign].[DBS_DTBS] (
    [DTBS_ID]   VARCHAR (128) NOT NULL,
    [DTBS]      IMAGE         NOT NULL,
    [DTBS_DATE] DATETIME      NOT NULL,
    [SIGNATURE] IMAGE         NULL,
    PRIMARY KEY CLUSTERED ([DTBS_ID] ASC)
);
GO

