CREATE TABLE [DBSign].[DBS_APP_FUNCTION] (
    [APP_LIBRARY_NAME] VARCHAR (255) NOT NULL,
    [FUNCTION_NAME]    VARCHAR (255) NOT NULL,
    [TEMPLATE_NAME]    VARCHAR (255) NOT NULL,
    [FUNCTION_CODE]    VARCHAR (1)   NOT NULL
);
GO

